"""Judge/extractor endpoints (OpenAI-compatible vLLM), JSON-schema outputs, temperature 0, disk cache."""

from __future__ import annotations

import hashlib
import json
import threading
import time
from pathlib import Path
from typing import Any

import openai

# Candidate judges. Family = model lineage; a judge is never used on episodes generated by its own family.
JUDGES: dict[str, dict[str, Any]] = {
    "gemma_4_31b": {"base_url": "http://127.0.0.1:8103/v1", "family": "gemma"},
    "mistral_small_24b": {"base_url": "http://127.0.0.1:8310/v1", "family": "mistral"},
    "qwen3_14b": {"base_url": "http://127.0.0.1:8309/v1", "family": "qwen",
                  "extra_body": {"chat_template_kwargs": {"enable_thinking": False}}},
    "granite_41_30b": {"base_url": "http://127.0.0.1:8322/v1", "family": "granite"},
    "nemotron_super_49b": {"base_url": "http://127.0.0.1:8313/v1", "family": "llama",
                           "system_prefix": "detailed thinking off\n\n"},
}
GENERATOR_FAMILY = {"gemma4_31b": "gemma", "granite41_8b": "granite", "llama31_8b": "llama",
                    "mistral_small_24b": "mistral", "qwen3_14b": "qwen", "qwen3_4b": "qwen"}


def eligible(judge: str, generator: str) -> bool:
    return JUDGES[judge]["family"] != GENERATOR_FAMILY[generator]


class Cache:
    """Append-only JSONL cache keyed by sha256(model, messages, schema, max_tokens)."""

    def __init__(self, path: Path):
        self.path = path
        self.lock = threading.Lock()
        self.data: dict[str, dict] = {}
        if path.exists():
            for line in path.read_text(encoding="utf-8").splitlines():
                try:
                    row = json.loads(line)
                    self.data[row["k"]] = row
                except (json.JSONDecodeError, KeyError):
                    continue
        path.parent.mkdir(parents=True, exist_ok=True)
        self.fh = path.open("a", encoding="utf-8")

    @staticmethod
    def key(model: str, messages: list[dict], schema: dict, max_tokens: int) -> str:
        blob = json.dumps([model, messages, schema, max_tokens], sort_keys=True)
        return hashlib.sha256(blob.encode()).hexdigest()

    def get(self, k: str) -> dict | None:
        return self.data.get(k)

    def put(self, row: dict) -> None:
        with self.lock:
            self.data[row["k"]] = row
            self.fh.write(json.dumps(row) + "\n")
            self.fh.flush()


class JudgeLLM:
    def __init__(self, name: str, cache: Cache, max_tokens: int = 700):
        spec = JUDGES[name]
        self.name = name
        self.spec = spec
        self.client = openai.OpenAI(base_url=spec["base_url"], api_key="EMPTY", timeout=300, max_retries=0)
        self.cache = cache
        self.max_tokens = max_tokens

    def ask(self, system: str, user: str, schema: dict, max_tokens: int | None = None) -> dict:
        """Return {"parsed": dict|None, "raw": str, "error": str|None}. Cached; errors are not cached."""
        mt = max_tokens or self.max_tokens
        messages = [{"role": "system", "content": self.spec.get("system_prefix", "") + system},
                    {"role": "user", "content": user}]
        k = Cache.key(self.name, messages, schema, mt)
        hit = self.cache.get(k)
        if hit is not None:
            return hit
        kwargs: dict[str, Any] = {
            "model": self.name, "messages": messages, "temperature": 0.0, "seed": 0, "max_tokens": mt,
            "response_format": {"type": "json_schema", "json_schema": {"name": "answer", "schema": schema,
                                                                       "strict": True}},
        }
        if self.spec.get("extra_body"):
            kwargs["extra_body"] = self.spec["extra_body"]
        err = None
        for attempt in range(5):
            try:
                resp = self.client.chat.completions.create(**kwargs)
                raw = resp.choices[0].message.content or ""
                finish = resp.choices[0].finish_reason
                try:
                    parsed = json.loads(raw)
                except json.JSONDecodeError:
                    parsed = None
                row = {"k": k, "model": self.name, "parsed": parsed, "raw": raw[:4000], "finish": finish,
                       "error": None if parsed is not None else "unparseable"}
                self.cache.put(row)
                return row
            except openai.BadRequestError as exc:
                err = f"bad_request: {str(exc)[:300]}"
                break
            except (openai.APIConnectionError, openai.APITimeoutError, openai.InternalServerError,
                    openai.RateLimitError) as exc:
                err = f"infra: {str(exc)[:300]}"
                time.sleep(3 * (attempt + 1))
        return {"k": k, "model": self.name, "parsed": None, "raw": "", "error": err}
