"""E11 step 8: write results/v3/e11/E11_REPORT.md from the CSV/JSON outputs (every number comes from them)."""

from __future__ import annotations

import json

import pandas as pd
from common import OUT, read_jsonl

J_SHORT = {"gemma_4_31b": "gemma-4-31B", "mistral_small_24b": "Mistral-Small-24B", "qwen3_14b": "Qwen3-14B",
           "granite_41_30b": "Granite-4.1-30B", "nemotron_super_49b": "Nemotron-Super-49B"}


def pct(x: float, d: int = 1) -> str:
    return "–" if pd.isna(x) else f"{100 * x:.{d}f}"


def ci(row, k: str, d: int = 1) -> str:
    if k not in row or pd.isna(row[k]):
        return "–"
    return f"{pct(row[k], d)} [{pct(row[k + '_lo'], d)}, {pct(row[k + '_hi'], d)}]"


def md_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(map(str, cols)) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for r in df.itertuples(index=False):
        lines.append("| " + " | ".join(map(str, r)) + " |")
    return "\n".join(lines)


def main() -> None:
    sample = pd.read_csv(OUT / "sample.csv")
    episodes = pd.DataFrame(read_jsonl(OUT / "episodes.jsonl"))
    claims = pd.DataFrame(read_jsonl(OUT / "claims.jsonl"))
    agree = pd.read_csv(OUT / "agreement.csv")
    val = pd.read_csv(OUT / "judge_validation.csv")
    vtype = pd.read_csv(OUT / "judge_validation_by_type.csv")
    vj = json.loads((OUT / "validated_judges.json").read_text())
    pert = pd.DataFrame(read_jsonl(OUT / "perturbations.jsonl"))
    m_sa = pd.read_csv(OUT / "metrics_system_arm.csv")
    m_s = pd.read_csv(OUT / "metrics_system.csv")
    m_sma = pd.read_csv(OUT / "metrics_system_model_arm.csv")
    m_corr = pd.read_csv(OUT / "metrics_by_correctness.csv")
    m_judge = pd.read_csv(OUT / "metrics_per_judge.csv")
    dcr = pd.read_csv(OUT / "dc_records.csv")
    dcf = json.loads((OUT / "dc_records_fields.json").read_text())
    dist = pd.read_csv(OUT / "judge_label_distribution.csv")
    cs = pd.read_csv(OUT / "claim_scores.csv")

    L: list[str] = []
    w = L.append
    w("# E11 — Analyst-response quality (validated synthesis, gap G2)\n")
    w("All numbers below are produced by `scripts/e11/*.py` (run `scripts/e11/run_all.sh`; LLM calls are cached in "
      "`results/v3/e11/cache/`). Analysis rules were fixed in `PROTOCOL.md` before system-level results were "
      "computed.\n")

    # ------------------------------------------------------------------ setup
    w("## 1. Setup\n")
    n_ep = len(episodes)
    w(f"- Episodes: {n_ep} frozen v2 test episodes (`runs/test/E2`), {sample.case_id.nunique()} distinct cases "
      f"({sample.cve.nunique()} CVEs), stratified by variant; {sample.groupby(['system', 'arm']).size().min()} "
      "episodes per system x arm pooled over the six generators (30 cases per generator, all 5 systems x 2 arms on "
      f"each). Episodes with a recorded error: {int(episodes.error.sum())}. Evidence replay mismatches: "
      f"{int((episodes.replay_mismatch.str.len() > 0).sum())} (every replayed tool output equals its recorded "
      "prefix, id and status).")
    n_zero = int((episodes.n_claims == 0).sum())
    zero_by = episodes[episodes.n_claims == 0].groupby("system").size().to_dict()
    w(f"- Claims: {len(claims)} atomic claims extracted (gemma-4-31B; Granite-4.1-30B for gemma-generated "
      f"episodes); {n_zero} episodes yielded no claim ({zero_by}). Extraction fidelity check (every version string "
      f"and call id in a claim occurs in the source explanation): {pct(claims.fidelity_ok.mean(), 2)}% of claims.")
    w("- Judges: five candidate judges from five families (gemma, mistral, qwen, granite, llama-lineage Nemotron), "
      "per-claim calls with JSON-schema output at temperature 0; a judge is never applied to episodes generated by "
      "its own family. The DC primary evidence includes the controller evidence state that DC's response prompt "
      "received; a no-state sensitivity is reported.\n")

    # ------------------------------------------------------------------ validation
    w("## 2. Judge validation (no humans)\n")
    w("### 2a. Inter-judge agreement\n")
    fl = agree[agree.pair.str.startswith("fleiss")].copy()
    fl["kappa"] = fl.kappa.map(lambda x: f"{x:.3f}")
    fl["pct_agree"] = fl.pct_agree.map(lambda x: f"{100 * x:.1f}% (all 5 agree)")
    fl["pct_agree"] = [x.replace("all 5", "all " + p.split("(")[1].split(")")[0]) for x, p in zip(fl.pct_agree, fl.pair)]
    fl["judges"] = fl.pair.map(lambda p: "all 5 candidates" if p == "fleiss(5)" else "3 validated")
    w(md_table(fl[["what", "scheme", "judges", "n_items", "kappa", "pct_agree"]]))
    w("(For asserted status, `binary` = affected vs any other answer.)\n")
    w("")
    pw = agree[(~agree.pair.str.startswith("fleiss")) & (agree.what == "claim_label")].copy()
    piv = pw.pivot(index="pair", columns="scheme", values="kappa").reset_index()
    for c in piv.columns[1:]:
        piv[c] = piv[c].map(lambda x: f"{x:.3f}")
    w("Pairwise Cohen κ on claim labels:\n")
    w(md_table(piv))
    w("")
    dist = dist.rename(columns={"judge": "judge"})
    for c in dist.columns[1:]:
        dist[c] = dist[c].map(lambda x: f"{100 * x:.1f}%")
    w("Label distribution per judge (all claims, main mode):\n")
    w(md_table(dist))
    w("")
    w("### 2b. Perturbation test\n")
    kinds = pert.kind.value_counts().to_dict()
    w(f"Injected errors: {sum(v for k, v in kinds.items() if k != 'control')} "
      f"({', '.join(f'{k}: {v}' for k, v in sorted(kinds.items()) if k != 'control')}); untouched controls: "
      f"{kinds.get('control', 0)}. Scored per judge on items whose base claim is supported by >= 3 of the other "
      "4 judges (leave-one-out). Rule (pre-specified): recall >= 0.85 and false alarm <= 0.10.\n")
    vt = val.copy()
    vt["recall [95% Wilson]"] = vt.apply(lambda r: f"{r.recall:.3f} [{r.recall_lo:.3f}, {r.recall_hi:.3f}]", axis=1)
    vt["false alarm [95% Wilson]"] = vt.apply(
        lambda r: f"{r.false_alarm:.3f} [{r.fa_lo:.3f}, {r.fa_hi:.3f}]", axis=1)
    vt["passes"] = vt.passes.map({True: "**yes**", False: "no"})
    w(md_table(vt[["judge", "n_injected", "recall [95% Wilson]", "n_controls", "false alarm [95% Wilson]",
                   "judge_errors", "passes"]]))
    w("")
    tp = vtype.pivot(index="judge", columns="kind", values="rate").reset_index()
    for c in tp.columns[1:]:
        tp[c] = tp[c].map(lambda x: f"{x:.3f}")
    w("Flag rate by edit type (for `control` this is the false-alarm rate):\n")
    w(md_table(tp))
    w("")
    w(f"**Validated judges: {', '.join(vj['validated']) if vj['validated'] else 'none'}** "
      f"({'at least two pass' if vj['enough'] else 'FEWER THAN TWO PASS — main metrics are not validated'}).\n")

    # ------------------------------------------------------------------ main metrics
    w("## 3. Response quality per system x arm (pooled over generators)\n")
    w("Soft labels: each claim scores the fraction of eligible validated judges (validated and not of the "
      "generator's family) giving a label. Percentages with 95% CVE-clustered bootstrap CIs (2,000 resamples).\n")
    t = m_sa.copy()
    out = pd.DataFrame({
        "system": t.system, "arm": t.arm, "episodes": t.n_episodes, "claims": t.n_claims,
        "faithfulness %": t.apply(lambda r: ci(r, "faithfulness"), axis=1),
        "contradicted %": t.apply(lambda r: ci(r, "contradicted"), axis=1),
        "not in evidence %": t.apply(lambda r: ci(r, "not_in_evidence"), axis=1),
        "expl.–decision consistency %": t.apply(lambda r: ci(r, "consistency"), axis=1),
        "chars (mean)": t.chars_mean.map(lambda x: f"{x:.0f}"),
        "claims/ep.": t.claims_per_episode.map(lambda x: f"{x:.2f}"),
    })
    w(md_table(out))
    w("")
    w("Hallucination rate = contradicted + not in evidence = 100 − faithfulness.\n")
    w("Pooled over arms:\n")
    t = m_s.copy()
    out = pd.DataFrame({"system": t.system, "episodes": t.n_episodes, "claims": t.n_claims,
                        "faithfulness %": t.apply(lambda r: ci(r, "faithfulness"), axis=1),
                        "hallucination %": t.apply(lambda r: ci(r, "hallucination"), axis=1),
                        "consistency %": t.apply(lambda r: ci(r, "consistency"), axis=1),
                        "asserts no status %": t.asserted_none.map(pct)})
    w(md_table(out))
    w("")
    w("### Citation validity\n")
    t = m_sa[m_sa.n_cited_claims > 0].copy()
    out = pd.DataFrame({"system": t.system, "arm": t.arm, "claims citing a call id": t.n_cited_claims,
                        "share of claims citing %": t.share_claims_cited.map(pct),
                        "cited ids that exist %": t.cite_id_exist.map(pct),
                        "citation validity % (ids exist AND cited outputs support the claim)":
                            t.apply(lambda r: ci(r, "citation_validity"), axis=1)})
    w(md_table(out))
    w("")
    w("### DC sensitivity: evidence without the controller state\n")
    t = m_sa[m_sa.system == "DC"]
    out = pd.DataFrame({"arm": t.arm, "faithfulness % (tool outputs + [state], primary)":
                        t.apply(lambda r: ci(r, "faithfulness"), axis=1),
                        "faithfulness % (tool outputs only)": t.apply(lambda r: ci(r, "faithfulness_nostate"), axis=1)})
    w(md_table(out))
    w("")
    w("### Per generator (faithfulness %, point estimates; CIs in `metrics_system_model_arm.csv`)\n")
    pv = m_sma.pivot_table(index=["system", "arm"], columns="model", values="faithfulness").reset_index()
    for c in pv.columns[2:]:
        pv[c] = pv[c].map(pct)
    w(md_table(pv))
    w("")
    pv = m_sma.pivot_table(index=["system", "arm"], columns="model", values="consistency").reset_index()
    for c in pv.columns[2:]:
        pv[c] = pv[c].map(pct)
    w("Explanation–decision consistency % per generator:\n")
    w(md_table(pv))
    w("")
    w("### Faithfulness by decision correctness (submitted status vs sealed test label)\n")
    t = m_corr.copy()
    out = pd.DataFrame({"system": t.system, "decision correct": t.correct, "episodes": t.n_episodes,
                        "claims": t.n_claims, "faithfulness %": t.apply(lambda r: ci(r, "faithfulness"), axis=1),
                        "consistency %": t.apply(lambda r: ci(r, "consistency"), axis=1)})
    w(md_table(out))
    w("")
    w("### Per-judge sensitivity (faithfulness %, each validated judge on the episodes it is eligible for)\n")
    pj = m_judge.pivot_table(index=["system", "arm"], columns="judge", values="faithfulness").reset_index()
    for c in pj.columns[2:]:
        pj[c] = pj[c].map(pct)
    w(md_table(pj))
    w("")

    # ------------------------------------------------------------------ DC records
    w("## 4. DC validation / repair / fallback in the raw records\n")
    keys = dcf["record_keys_matching_repair_fallback_valid_retry"]
    tot = dcr[dcr.model == "ALL"].iloc[0]
    w(f"- Searched every DC test record ({int(tot.n_dc_episodes)} episodes: 6 generators x 2 arms x 453 cases) for "
      f"fields matching `{dcf['note'].split('regex ')[-1]}` (outside `calls`/`trace`): "
      f"**{len(keys)} such fields{': ' + ', '.join(keys) if keys else ''}**. The v2 records contain **no "
      "information about response validation, repair or fallback**, and the v2 DC code path that produced them "
      "(`Controller._explain`) issues one LLM call with no citation/claim check, no repair attempt and no "
      "deterministic fallback. Repair and fallback rates on real data therefore cannot be reported from v2; the "
      "claim/citation checks in §3 are what such a validator would have measured post hoc.")
    w("- What the records do contain is the verdict log of the *extraction* verifier (a different stage: LLM "
      "version-extraction proposals checked against the tool output): "
      + "; ".join(f"{k}: {v}" for k, v in dcf["extraction_verifier_verdicts"].items()) + ".")
    w(f"- Deterministic checks over all DC explanations: empty {int(tot.empty_explanation)}; with >= 1 call-id "
      f"citation {int(tot.with_call_id_citation)} ({pct(tot.share_with_citation)}%); cited call ids that exist in "
      f"the episode {int(tot.cited_ids_existing)}/{int(tot.cited_call_ids)} ({pct(tot.share_cited_ids_existing, 2)}%); "
      f"explanations that hit the 200-token limit (episodes whose only LLM call was the explanation and whose usage "
      f"records a length truncation) {int(tot.explain_call_hit_max_tokens)}/{int(tot.single_llm_call_episodes)}.")
    t = dcr[dcr.model != "ALL"]
    out = pd.DataFrame({"generator": t.model, "arm": t.arm, "with citation %": t.share_with_citation.map(pct),
                        "cited ids existing": t.apply(lambda r: f"{int(r.cited_ids_existing)}/{int(r.cited_call_ids)}",
                                                      axis=1),
                        "hit token limit": t.apply(
                            lambda r: f"{int(r.explain_call_hit_max_tokens)}/{int(r.single_llm_call_episodes)}", axis=1)})
    w("")
    w(md_table(out))
    w("")
    posthoc(w, m_sa, OUT)
    summary = findings(m_sa, m_s, val, vj, agree, m_corr, dcr, m_judge)
    limitations(w, val, m_sa, pert, vj)
    L[2:2] = summary
    (OUT / "E11_REPORT.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", OUT / "E11_REPORT.md", len(L), "lines;", len(cs), "scored claims")


def posthoc(w, m_sa: pd.DataFrame, out) -> None:
    w("## 5. Secondary and post-hoc analyses (not pre-specified; see PROTOCOL.md, Deviations)\n")
    d = pd.read_csv(out / "diff_dc_vs_baselines.csv")
    t = pd.DataFrame({"arm": d.arm, "baseline": d.baseline,
                      "Δ faithfulness DC − baseline (pp)": d.apply(lambda r: ci(r, "d_faithfulness"), axis=1),
                      "Δ consistency DC − baseline (pp)": d.apply(lambda r: ci(r, "d_consistency"), axis=1)})
    w("### DC minus each baseline (paired by case within generator; CVE-clustered paired bootstrap)\n")
    w(md_table(t))
    w("")
    dj = pd.read_csv(out / "diff_dc_vs_baselines_per_judge.csv")
    dj["cell"] = dj.apply(lambda r: f"{100 * r.d_faithfulness:+.1f} [{100 * r.lo:+.1f}, {100 * r.hi:+.1f}]", axis=1)
    pj = dj.pivot_table(index=["arm", "baseline"], columns="judge", values="cell", aggfunc="first").reset_index()
    w("Per validated judge (Δ faithfulness, pp):\n")
    w(md_table(pj))
    w("")
    w("### Coarse explanation–decision consistency (fixed and not_affected merged)\n")
    t = pd.DataFrame({"system": m_sa.system, "arm": m_sa.arm,
                      "strict % (primary)": m_sa.apply(lambda r: ci(r, "consistency"), axis=1),
                      "coarse %": m_sa.apply(lambda r: ci(r, "consistency_coarse"), axis=1),
                      "asserts no status %": m_sa.asserted_none.map(pct)})
    w(md_table(t))
    w("")
    w("### Citation failures: contradicted vs insufficient\n")
    c = m_sa[m_sa.n_cited_claims > 0]
    t = pd.DataFrame({"system": c.system, "arm": c.arm, "cited claims": c.n_cited_claims,
                      "valid %": c.apply(lambda r: ci(r, "citation_validity"), axis=1),
                      "cited outputs contradict the claim %": c.apply(lambda r: ci(r, "citation_contradicted"), axis=1)})
    w(md_table(t))
    w("The remainder (100 − valid − contradicted, plus missing ids) is *insufficient*: the cited outputs exist but do "
      "not by themselves establish the claim.\n")
    w("### Status/conclusion claims vs factual-detail claims\n")
    ct = pd.read_csv(out / "metrics_by_claim_type.csv")
    t = pd.DataFrame({"system": ct.system, "arm": ct.arm,
                      "claim type": ct.status_claim.map({True: "status/conclusion", False: "factual detail"}),
                      "claims": ct.n_claims, "faithfulness %": ct.apply(lambda r: ci(r, "faithfulness"), axis=1),
                      "contradicted %": ct.apply(lambda r: ci(r, "contradicted"), axis=1),
                      "not in evidence %": ct.apply(lambda r: ci(r, "not_in_evidence"), axis=1)})
    w(md_table(t))
    w("")
    w("### By arm x decision correctness\n")
    ac = pd.read_csv(out / "metrics_by_arm_correctness.csv")
    t = pd.DataFrame({"system": ac.system, "arm": ac.arm, "decision correct": ac.correct, "episodes": ac.n_episodes,
                      "faithfulness %": ac.apply(lambda r: ci(r, "faithfulness"), axis=1),
                      "contradicted %": ac.apply(lambda r: ci(r, "contradicted"), axis=1),
                      "consistency %": ac.apply(lambda r: ci(r, "consistency"), axis=1)})
    w(md_table(t))
    w("")


def g(df: pd.DataFrame, **kw) -> pd.Series:
    m = df
    for k, v in kw.items():
        m = m[m[k] == v]
    assert len(m) == 1, kw
    return m.iloc[0]


def findings(m_sa, m_s, val, vj, agree, m_corr, dcr, m_judge) -> list[str]:
    out = OUT
    f = []
    a = f.append
    a("## Key findings\n")
    fl5 = agree[(agree.pair == "fleiss(5)") & (agree.what == "claim_label") & (agree.scheme == "3-class")].iloc[0]
    flb = agree[(agree.pair == "fleiss(5)") & (agree.what == "claim_label") & (agree.scheme == "binary")].iloc[0]
    v = val.set_index("judge")
    passed = vj["validated"]
    failed = [j for j in v.index if j not in passed]
    pert = pd.DataFrame(read_jsonl(out / "perturbations.jsonl"))
    cs = pd.read_csv(out / "claim_scores.csv")
    a(f"1. **Judge validation.** Five cross-family judges labelled {int(fl5.n_items)} claims; Fleiss κ = "
      f"{fl5.kappa:.2f} (3-class), {flb.kappa:.2f} (supported vs not). In the perturbation test "
      f"({int((pert.kind != 'control').sum())} injected errors, {int((pert.kind == 'control').sum())} controls; "
      f"{int(v.n_injected.min())}–{int(v.n_injected.max())} and {int(v.n_controls.min())}–{int(v.n_controls.max())} "
      "scored per judge after the leave-one-out filter) "
      + ", ".join(f"{J_SHORT[j]} recall {v.loc[j, 'recall']:.3f} / false alarm {v.loc[j, 'false_alarm']:.3f}"
                  for j in passed)
      + " passed the pre-specified rule (recall ≥ 0.85, false alarm ≤ 0.10); "
      + ", ".join(f"{J_SHORT[j]} ({v.loc[j, 'recall']:.3f} / {v.loc[j, 'false_alarm']:.3f})" for j in failed)
      + " failed (invented-id recall " + ", ".join(
          f"{J_SHORT[j]} {g(pd.read_csv(out / 'judge_validation_by_type.csv'), judge=j, kind='invented_id').rate:.3f}"
          for j in failed) + f"). Every scored claim has at least {int(cs.n_judges.min())} eligible validated judges."
      + (f" {J_SHORT['granite_41_30b']} passes narrowly (recall CI lower bound {v.loc['granite_41_30b', 'recall_lo']:.3f})."
         if "granite_41_30b" in passed else ""))
    dt, dw = g(m_sa, system="DC", arm="tracker"), g(m_sa, system="DC", arm="withheld")
    bt = m_sa[(m_sa.system != "DC") & (m_sa.arm == "tracker")]
    bw = m_sa[(m_sa.system != "DC") & (m_sa.arm == "withheld")]
    a(f"2. **Faithfulness.** With the tracker, DC's notes are {ci(dt, 'faithfulness')}% supported, statistically "
      f"indistinguishable from the ReAct baselines S3–S5 ({pct(bt[bt.system != 'S2'].faithfulness.min())}–"
      f"{pct(bt[bt.system != 'S2'].faithfulness.max())}%) and above one-shot S2 ({ci(g(m_sa, system='S2', arm='tracker'), 'faithfulness')}%). "
      f"Without the tracker every system drops (DC {ci(dw, 'faithfulness')}%, baselines "
      f"{pct(bw.faithfulness.min())}–{pct(bw.faithfulness.max())}%). Hallucination (contradicted + not in evidence) "
      f"is therefore {pct(1 - dt.faithfulness)}% (DC, tracker) to {pct(1 - dw.faithfulness)}% (DC, withheld)."
      + diff_sentence(out))
    a(f"3. **The note follows the decision.** Explanation–decision consistency is {ci(g(m_s, system='DC'), 'consistency')}% "
      f"for DC (the decision is fixed before the LLM writes) vs {ci(g(m_s, system='S2'), 'consistency')}% for S2 and "
      f"{pct(m_s[m_s.system.isin(['S3', 'S4', 'S5'])].consistency.min())}–"
      f"{pct(m_s[m_s.system.isin(['S3', 'S4', 'S5'])].consistency.max())}% for S3–S5. "
      + dc_inconsistency_sentence(out))
    a(f"4. **Citations exist but are often insufficient.** {pct(g(dcr, model='ALL', arm='ALL').share_with_citation)}% of "
      f"all {int(g(dcr, model='ALL', arm='ALL').n_dc_episodes)} DC notes cite call ids and "
      f"{pct(g(dcr, model='ALL', arm='ALL').share_cited_ids_existing, 2)}% of cited ids exist, but only "
      f"{ci(dt, 'citation_validity')}% (tracker) and {ci(dw, 'citation_validity')}% (withheld) of DC's cited claims are "
      "supported by the cited outputs alone. " + citation_tool_sentence(out) + " Cited outputs contradict the claim in "
      f"{pct(dt.citation_contradicted)}% (tracker) and {pct(dw.citation_contradicted)}% (withheld) of cited claims.")
    a("5. **Unfaithful notes accompany wrong decisions.** Pooled over arms, faithfulness is "
      + "; ".join(f"{s} {pct(g(m_corr, system=s, correct=True).faithfulness)}% when the decision is correct vs "
                  f"{pct(g(m_corr, system=s, correct=False).faithfulness)}% when wrong" for s in ["DC", "S2", "S3", "S4", "S5"])
      + ".")
    a("6. **Validation / repair / fallback.** The v2 DC records contain no response-validation, repair or fallback "
      "information, and the v2 code had none (single LLM call). The paper's 'validated synthesis' (§III-D) was not "
      "exercised in v2; the rates above are what a post-hoc validator measures, not what a deployed one did (§4).")
    a(f"7. **DC's evidence view matters.** Judged against the raw tool outputs only (without the controller state DC's "
      f"prompt contained), DC faithfulness falls to {ci(dt, 'faithfulness_nostate')}% (tracker) and "
      f"{ci(dw, 'faithfulness_nostate')}% (withheld), i.e. a sizeable share of DC claims is supported only through the "
      "controller's belief state (atom values, source groups), not directly by a tool output. Against raw outputs "
      "alone DC would rank below the baselines; which view is right depends on whether the verified state counts "
      "as evidence for the analyst.\n")
    return f


def diff_sentence(out) -> str:
    d = pd.read_csv(out / "diff_dc_vs_baselines.csv")
    t = d[(d.arm == "tracker") & (d.baseline.isin(["S3", "S4", "S5"]))]
    s2 = g(d, arm="tracker", baseline="S2")
    dj = pd.read_csv(out / "diff_dc_vs_baselines_per_judge.csv")
    w = dj[dj.arm == "withheld"].groupby("judge").d_faithfulness.agg(["min", "max"])
    neg = [J_SHORT[j] for j, r in w.iterrows() if r["max"] < 0]
    posj = [J_SHORT[j] for j, r in w.iterrows() if r["min"] > 0]
    return (f" Paired differences DC − S3/S4/S5 with the tracker are {', '.join(ci(r, 'd_faithfulness') for _, r in t.iterrows())} pp "
            f"(DC − S2: {ci(s2, 'd_faithfulness')} pp). In the withheld arm the sign depends on the judge: "
            f"{' and '.join(neg) or 'no judge'} rate DC below all four baselines, {' and '.join(posj) or 'no judge'} above "
            "all four (§5), so no ordering of DC against the baselines is claimed there.")


def dc_inconsistency_sentence(out) -> str:
    e = pd.read_csv(out / "episode_scores.csv")
    x = e[(e.system == "DC") & (e.consistent < 1)]
    by = x.groupby(["model", "arm"]).size()
    parts = ", ".join(f"{m}/{a}: {n}" for (m, a), n in by.items())
    return (f"DC episodes with any judge reading a different status from the note: {len(x)} ({parts}); inspection "
            "shows llama31_8b notes asserting both 'affected' and 'fix applied'.")


def citation_tool_sentence(out) -> str:
    t = pd.read_csv(out / "dc_citation_tools.csv")
    tr = t[t.arm == "tracker"]
    pk = tr[tr.tool == "pkg_query"].n_cited_ids.sum()
    inval = tr[~tr.valid]
    return (f"With the tracker, {pk} of {tr.n_cited_ids.sum()} ids cited in DC claims point to package-query outputs, "
            f"including {inval[inval.tool == 'pkg_query'].n_cited_ids.sum()} of the {inval.n_cited_ids.sum()} ids behind "
            "invalid citations. Typical invalid cases (from `claims.jsonl`): '…is within the affected version range "
            "[c002]', '…the fix … has been verified to be present in the system [c002]' — the cited output is the "
            "installed-version record, while the range/fix conclusion also needs the tracker's fixed version, which "
            "is not cited.")


def limitations(w, val, m_sa, pert, vj) -> None:
    w("## 6. Limitations\n")
    miss = vj.get("perturbations_missed_by_all_judges", {})
    w("- No human labels. Judge validity rests on (a) agreement among five cross-family judges and (b) recall of "
      "synthetic, deterministic edits; the edits are minimal and lexical (version bump, negation, status swap, absent "
      "id), so recall on subtler real errors (wrong reasoning, partially supported claims) may be lower. Perturbed "
      f"items that all five judges still label supported (candidate non-errors): {sum(miss.values())} "
      f"({', '.join(f'{k}: {v}' for k, v in miss.items())}). Some edits are ungrammatical (e.g. double negation).")
    w(f"- The main metric averages {len(vj['validated'])} validated judges whose levels differ (per-judge tables in §3 and §5); "
      + f"{J_SHORT[str(pd.read_csv(OUT / 'judge_label_distribution.csv').set_index('judge').supported.idxmax())]} labels the "
      "most claims supported and Granite-4.1-30B passes the rule only narrowly, so absolute faithfulness "
      "levels carry judge uncertainty beyond the bootstrap CIs, which cover only CVE sampling.")
    w("- Claims are extracted by one LLM (gemma-4-31B, or Granite-4.1-30B for gemma-generated notes), which is also a "
      "judge for non-gemma episodes; extraction was checked only for lexical fidelity (versions and ids copied from "
      f"the note). {int((pert.kind == 'wrong_version').sum())} wrong-version perturbations come from S2–S5 only "
      "because DC notes rarely contain version strings.")
    w("- Notes are scored against the outputs the system observed (S2 2,500 chars per output; S3–S5 3,000; DC 3,000 "
      "plus the controller evidence state). A claim that is true of the host but absent from those outputs counts as "
      "not in evidence; 'supported' does not mean the decision is correct.")
    w("- The sample is 180 cases (83 CVEs), 30 per generator; per-generator cells have wide CIs "
      "(`metrics_system_model_arm.csv`). Recorded explanations were capped at 1,500 characters by the v2 runner.")
    w("- Temperature-0 judging is not bit-deterministic under vLLM batching; reported numbers are fixed by the response "
      "cache (`cache/`), see PROTOCOL.md Deviations 4.")
    w("- Status-claim vs detail split, coarse consistency, citation-contradiction split, per-judge differences and "
      "DC-minus-baseline differences are post hoc / secondary.\n")
    w("## Files\n")
    w("`PROTOCOL.md` (pre-specified rules), `sample.csv`, `episodes.jsonl`, `claims.jsonl`, `judgments.jsonl`, "
      "`status_judgments.jsonl`, `perturbations.jsonl`, `perturb_judgments.jsonl`, `agreement.csv`, "
      "`judge_label_distribution.csv`, `judge_validation.csv`, `judge_validation_by_type.csv`, "
      "`validated_judges.json`, `claim_scores.csv`, `episode_scores.csv`, `metrics_system_arm.csv`, "
      "`metrics_system.csv`, `metrics_system_model_arm.csv`, `metrics_by_correctness.csv`, "
      "`metrics_by_arm_correctness.csv`, `metrics_by_claim_type.csv`, `metrics_per_judge.csv`, "
      "`diff_dc_vs_baselines.csv`, `diff_dc_vs_baselines_per_judge.csv`, `dc_citation_tools.csv`, `dc_records.csv`, `dc_records_fields.json`, "
      "`cache/` (all LLM responses). Code: `src/deepcti/judge/`, `scripts/e11/`, tests `tests/v3/test_e11_*.py`.")

if __name__ == "__main__":
    main()
