"""Render results/v2/e7/E7_REPORT.md from the CSV/JSON produced by score_e7.py.
Every number in the tables is read from those files; the narrative text is fixed
except for the 'Findings' block which is read from results/v2/e7/findings.md if present."""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "results/v2/e7"
summ = list(csv.DictReader((OUT / "e7_summary.csv").open()))
seeds = list(csv.DictReader((OUT / "e7_per_seed.csv").open()))
diag = json.loads((OUT / "e7_diagnostics.json").read_text())
cases = list(csv.DictReader((OUT / "e7_per_case.csv").open()))


def f(x, d=3):
    return "n/a" if x in (None, "", "None") else f"{float(x):.{d}f}"


def pm(r, k, d=3):
    return f"{f(r[k + '_mean'], d)} ± {f(r[k + '_sd'], d)}"


lines = []
A = lines.append
A("# E7: Does DeepCTI's evidence-state discipline transfer to VEX-Bench?\n")
A("*Generated by `scripts/e7/make_report.py` from `e7_summary.csv`, `e7_per_seed.csv`, `e7_per_case.csv` and `e7_diagnostics.json`. All metric values come from VEX-Bench's own `evaluate.metrics.compute_metrics`, called by `scripts/e7/score_e7.py`.*\n")
A("## Question\n")
A("VEX-Bench (Shi et al., arXiv 2609.08040, MIT) is a static task built by someone else. Given a repository snapshot and a CVE, an agent decides whether the CVE is exploitable in that repository and gives one of 12 justification categories. E7 asks whether wrapping the same agent harness with DeepCTI's evidence-state discipline helps on this task. The discipline is: span-pointed atoms, a deterministic verifier, a fixed decision rule, greedy acquisition and a stopping rule. A null or negative answer is a valid result.\n")
A("## Setup\n")
A(f"* **Data:** VEX-Bench commit `80cddea`, 62 of the 75 tasks (see Deviations). The labels are the benchmark's own ground truth, unchanged. Ground-truth categories in the subset: {json.dumps(diag['gt_category'])}.")
A("* **Models:** Gemma-4-31B-it (`gemma_4_31b`) and Qwen3-14B (`qwen3_14b`, thinking disabled), served by vLLM through the OpenAI tools API.")
A("* **Sampling:** temperature 0.7. There are 3 independent runs, with seeds 0, 1 and 2 passed as the per-request `seed`. Concurrency was at most 8 per server.")
A("* **Budgets, identical for A and B:**")
A("  * at most 30 code-tool calls, each costing 1 unit;")
A("  * at most 45 LLM turns;")
A("  * a 600 s wall clock, the same as VEX-Bench's default timeout;")
A("  * at most 2048 output tokens per turn;")
A("  * the same context-trimming policy: once the transcript passes 60k characters, the oldest tool outputs are elided.")
A("* **Tools:** `list_dir`, `read_file` (line ranges, at most 150 lines), `grep` (ERE, optional glob) and `find_symbol_usages` (whole-word search over source files, with test and vendor hits tagged).")
A("  * All tools are read-only. Paths are resolved and confined to the case checkout, and there is no network access.")
A("  * Outputs are truncated at 6000 characters.")
A("  * Code: `src/deepcti/vexbench/tools.py`.")
A("* **Task description, identical for A and B:**")
A("  * VEX-Bench's own prompt `evaluate.prompts.VULNERABILITY_ANALYSIS_PROMPT`, used verbatim;")
A("  * a short environment note (no network, the tool names, the budget, the language);")
A("  * an offline advisory digest built from OSV and the GitHub Advisory DB: summary, CWE, affected packages and ranges, Go import paths and symbols, and details. All URLs are removed.")
A("* **System A (open harness):** a ReAct loop. The model stops calling tools and returns VEX-Bench's JSON `{category, reasoning}`.")
A("  * If the budget runs out, one final answer is requested with `tool_choice=none`.")
A("  * Up to 2 nudges are sent when the reply cannot be parsed.")
A("  * The output is parsed with VEX-Bench's `parse_category`.")
A("* **System B (evidence-state discipline):** the same loop and tools, plus `propose_atom` and `finish`. B uses a different output channel from A: the LLM never outputs a category.")
A("  * **Atoms:** dependency_present, vulnerable_version_used, vulnerable_symbol_referenced, vulnerable_path_reachable_from_entry and mitigating_config. Each comes with spans (path, start_line, end_line, verbatim snippet).")
A("  * **Verifier (deterministic):** see `src/deepcti/vexbench/verifier.py`.")
A("    * A span is accepted only if the whitespace-stripped snippet occurs contiguously in those lines of the checkout.")
A("    * A symbol atom also needs an advisory symbol in the snippet. These are the explicit advisory symbols (Go vulndb, GHSA `vulnerable_functions`), or, if there are none, identifiers from the advisory text plus the package import names.")
A("    * A reachability atom needs 1-5 spans, all in non-test, non-vendored files, and the last span must contain a symbol.")
A("    * A version atom needs a package token and a version that falls inside or outside the advisory ranges, as claimed.")
A("    * A negative claim (dependency absent, package never referenced, referenced only from tests) is accepted only if the verifier's own repository-wide search confirms it.")
A("    * The atom state is Belnap-style: U/T/F, and B for conflicting accepted claims.")
A("  * **Decision rule (fixed, follows VEX-Bench's precedence):**")
A("    * R1: dep=F → code_not_present")
A("    * R2: version=F → code_not_present")
A("    * R3: dep=U → ABSTAIN")
A("    * R4: sym=F or reach=F → code_not_reachable")
A("    * R5: reach=T and mitig=T → requires_configuration")
A("    * R6: reach=T → vulnerable")
A("    * R7: otherwise → ABSTAIN")
A("  * **Abstention:** ABSTAIN is emitted as VEX-Bench's own fallback category `uncertain`, which maps to not_exploitable. The abstention rate is reported. This rule can never output requires_environment or the other protection categories.")
A("  * **Acquisition and stopping:**")
A("    * After every tool result, the controller appends the evidence state and names the first unresolved atom in decision-rule order as the next acquisition target, with a suggested sub-menu of tools.")
A("    * The run stops as soon as R1, R2, R4 or R5 fires.")
A("    * After R6 first holds, 4 more code-tool calls are allowed to look for a mitigation.")
A("    * Otherwise the run ends on `finish`, the budget or wall clock, or after 2 replies without a tool call.")
A("    * B's reasoning string is the list of accepted atoms with their spans.")
A("")
A("## Main results (mean ± sd over 3 runs; VEX-Bench metric code)\n")
A("| System | Model | Status F1 (exploitable) | Justification macro-F1 | Status acc. | Category acc. | Abstention rate | Mean tool calls / case | Mean tokens / case |")
A("|---|---|---|---|---|---|---|---|---|")
for r in summ:
    name = "A open harness" if r["system"] == "A" else "B + evidence state"
    A(f"| {name} | {r['model']} | {pm(r, 'status_f1')} | {pm(r, 'justif_macro_f1')} | {pm(r, 'status_accuracy')} | {pm(r, 'justif_accuracy')} | {pm(r, 'abstention')} | {pm(r, 'tool_calls', 1)} | {f(r['tokens_per_case_mean'], 0)} ± {f(r['tokens_per_case_sd'], 0)} |")
A("")
A("Notes on the table:\n")
A("* **Abstention:** for A, abstention means the answer was `uncertain` or could not be parsed. For B, it means the decision rule abstained.")
A("* **Tokens:** prompt plus completion tokens summed over all turns. The prompt is re-sent every turn and no prefix-cache credit is taken.")
A("* **Status precision/recall:** " + "; ".join(f"{r['system']}/{r['model']}: P={f(r['status_precision_mean'])} R={f(r['status_recall_mean'])}" for r in summ) + ".")
A("* **Answered cases:** " + "; ".join(f"{r['system']}/{r['model']} {r['cases_answered']}" for r in summ) + ".")
A("* **Selective accuracy on non-abstained answers** (status / category): " + "; ".join(f"{r['system']}/{r['model']} {f(r['selective_status_acc'])} / {f(r['selective_category_acc'])}" for r in summ) + ".")
A("* **Confusion totals over 3 runs:** " + "; ".join(f"{r['system']}/{r['model']} {r['binary_totals']}" for r in summ) + ".\n")
A("### Paired per-seed comparison (same seed, same tasks)\n")
A("| Model | Seed | Status F1 A | Status F1 B | Macro-F1 A | Macro-F1 B |")
A("|---|---|---|---|---|---|")
for s in seeds:
    A(f"| {s['model']} | {s['seed']} | {f(s['status_f1_A'])} | {f(s['status_f1_B'])} | {f(s['macro_f1_A'])} | {f(s['macro_f1_B'])} |")
A("")
bpath = OUT / "e7_bootstrap.csv"
if bpath.exists():
    A("### Paired task-level bootstrap, B − A (1000 resamples of tasks; metric = mean over 3 seeds)\n")
    A("| Model | Metric | Δ (B − A) | 95% CI | P_boot(Δ ≤ 0) |")
    A("|---|---|---|---|---|")
    for b in csv.DictReader(bpath.open()):
        A(f"| {b['model']} | {b['metric']} | {f(b['delta_B_minus_A'])} | [{f(b['ci95_lo'])}, {f(b['ci95_hi'])}] | {f(b['p_boot_delta_le_0'])} |")
    A("")
cpath = OUT / "e7_coverage_matched.csv"
if cpath.exists():
    A("### Coverage-matched comparison: only the (task, seed) pairs where B did not abstain (`scripts/e7/coverage_matched.py`)\n")
    A("| Model | System | Pairs | Status acc. | Category acc. | Exploitable share |")
    A("|---|---|---|---|---|---|")
    for c in csv.DictReader(cpath.open()):
        A(f"| {c['model']} | {c['system']} | {c['n_pairs']} | {f(c['status_acc'])} | {f(c['category_acc'])} | {f(c['exploitable_gt_share'])} |")
    A("")
A("### Trivial reference points (same subset, computed from ground truth)\n")
gt = [c for c in cases if c["system"] == summ[0]["system"] and c["model"] == summ[0]["model"] and c["seed"] == "0"]
n = len(gt)
pos = sum(c["gt"] == "exploitable" for c in gt)
f1_all_pos = 2 * pos / (n + pos) if n else 0
A(f"* Always predicting `vulnerable` gives status F1 = {f1_all_pos:.3f}, from {pos} exploitable cases out of {n}.")
A("* Always predicting a not_exploitable category gives status F1 = 0.000.\n")
A("## System B diagnostics\n")
for m in ["gemma_4_31b", "qwen3_14b"]:
    if m not in diag:
        continue
    d = diag[m]
    A(f"**{m}**\n")
    A(f"* Decision rule fired: `{json.dumps(d['rules'])}`")
    A(f"* End reasons: `{json.dumps(d['end_reasons'])}`")
    A(f"* Final atom states (runs × atoms): `{json.dumps(d['atom_states'])}`")
    A(f"* Proposals accepted/rejected and the top rejection reasons: `{json.dumps(d['proposals'])}`")
    A(f"* Predicted categories: `{json.dumps(d['pred_category'])}`")
    a = diag.get("A_" + m, {})
    A(f"* For comparison, System A's predicted categories: `{json.dumps(a.get('pred_category'))}`; end reasons: `{json.dumps(a.get('end_reasons'))}`\n")
fpath = OUT / "findings.md"
if fpath.exists():
    A("## Findings\n")
    A(fpath.read_text().strip() + "\n")
A("## Deviations from the VEX-Bench protocol\n")
A("1. **Subset of 62 of 75 tasks.**")
A("   * The full set of target checkouts is 7.09 GB (GitHub tree API), which is over the 5 GB budget, so the full download was not performed.")
A("   * Checkouts over 200 MB were excluded: 13 tasks (kubernetes ×4, cilium ×3, hadoop ×4, minikube, llama_index@c7d061e).")
A("   * The excluded tasks are skewed toward `vulnerable` (7 of 13) and Go (8 of 13). The subset has 15 of 62 exploitable cases, against 22 of 75 in the full benchmark, so absolute numbers are not comparable with the paper's.")
A("2. **No network.** VEX-Bench agents look the CVE up online; here both systems get the same offline OSV/GHSA digest with URLs removed. That digest probably carries more structured information (ranges, Go symbols) than an agent would gather on its own.")
A("3. **A custom ReAct harness and open-weight models** replace the Codex/Claude Code/OpenCode CLIs in Docker. The tools run on the host, read-only and path-sandboxed, instead of in a container.")
A("4. **Fixed sampling.** Temperature 0.7 and seeds 0, 1, 2 were fixed by the E7 brief; VEX-Bench sets no temperature. `--repeats 3` corresponds to the three seeds.")
A("5. **Restricted output range for B.** B's category comes from a fixed rule that can emit only code_not_present, code_not_reachable, requires_configuration, vulnerable or uncertain (abstain). requires_environment (2 ground-truth tasks in the subset) and the other protection categories are unreachable by design.")
A("6. **Pilot-driven fixes, made before the main run** (pilot: 2 tasks × Qwen and 3 tasks × Gemma, seed 0, discarded):")
A("   * mitigating_config spans that are only comments are rejected;")
A("   * a version atom may use 1-3 spans and the package's first '-'-stem, to handle Maven `${...version}` properties;")
A("   * the acquisition hint now says to submit an atom as soon as a span is available.")
A("   * Nothing was changed after the main runs started.\n")
A("## Files\n")
A("* Code: `src/deepcti/vexbench/{advisory,tools,verifier,agent}.py` and `scripts/e7/{make_subset,download_subset,fetch_advisories,run_e7,score_e7,make_report}.py`.")
A("* Raw runs: `runs/e7/<A|B>/<model>/<task_id>/run_00{1,2,3}/{result.json,trace.json,meta.json}`.")
A("* Logs: `logs/e7/`.")
A("* Scored data in VEX-Bench format: `results/v2/e7/vexbench_format/<sys>/<model>/{parsed.jsonl,metrics.json}`.")
A("* CSVs: `results/v2/e7/e7_summary.csv`, `e7_per_seed.csv` and `e7_per_case.csv`.")
(OUT / "E7_REPORT.md").write_text("\n".join(lines) + "\n")
print("wrote", OUT / "E7_REPORT.md")
