"""E11-D7b step 8 (POST HOC, D23): write results/v3/e11_d7b/E11_D7B_REPORT.md from the CSV/JSON outputs."""

from __future__ import annotations

import json

import numpy as np
import pandas as pd
from common_d7 import VALIDATED, read_jsonl
from common_d7b import OUT_A, OUT_B, SYSTEM_B
from d08_report import f3, md, pct

from deepcti.judge.stats import fleiss_kappa


def dci(r) -> str:
    return f"{r['diff']:+.3f} [{r.lo:+.3f}, {r.hi:+.3f}]"


def contrast_table(h: pd.DataFrame, sa: str, sb: str) -> str:
    d = h[(h.system_a == sa) & (h.system_b == sb)]
    names = {"sup": "faithfulness", "hal": "hallucination", "con": "contradicted", "nie": "not_in_evidence",
             "consistent": "expl–decision consistency", "cite_valid": "citation validity", "x": "faithfulness"}
    rows = [{"contrast": r.contrast, "metric": names.get(r.metric, r.metric), sa: f3(r.a), sb: f3(r.b),
             "diff [95% CI]": dci(r), "p (sign-flip)": f"{r.p_signflip:.4f}",
             "n claims/eps (a, b)": f"{r.n_a}, {r.n_b}", "cves": r.cves} for _, r in d.iterrows()]
    return md(pd.DataFrame(rows))


def main() -> None:
    R = json.loads((OUT_B / "h15b.json").read_text())
    h = pd.read_csv(OUT_B / "h15b_test.csv")
    hj = pd.read_csv(OUT_B / "h15b_per_judge.csv")
    sa = pd.read_csv(OUT_B / "metrics_system_arm.csv")
    ss = pd.read_csv(OUT_B / "metrics_system.csv")
    smm = pd.read_csv(OUT_B / "metrics_system_model_arm.csv")
    vo = pd.read_csv(OUT_B / "metrics_v21b_by_outcome.csv")
    rates = pd.read_csv(OUT_B / "v21b_synthesis_rates.csv")
    et = pd.read_csv(OUT_B / "v21b_attempt_error_types.csv")
    nc = pd.read_csv(OUT_B / "note_checks_same_triples.csv")
    sr = pd.read_csv(OUT_B / "status_readings.csv")
    rp = json.loads((OUT_B / "replay_check_x2b.json").read_text())
    eb = pd.DataFrame(read_jsonl(OUT_B / "episodes.jsonl"))
    ea = pd.DataFrame(read_jsonl(OUT_A / "episodes.jsonl"))
    jd = pd.DataFrame(read_jsonl(OUT_B / "judgments.jsonl"))
    sj = pd.DataFrame(read_jsonl(OUT_B / "status_judgments.jsonl"))
    bc, bv, vc = R[f"{SYSTEM_B}_vs_DC"], R[f"{SYSTEM_B}_vs_DCv21"], R["DCv21_vs_DC"]
    pr = h.set_index(h.system_a + ">" + h.system_b + "|" + h.contrast + "|" + h.metric)
    ni = bc["noninferior_at_margin"]
    L = []
    L.append("# E11-D7b — POST HOC: analyst-note faithfulness of DCv21b vs DC (and vs DCv21) on the H15 sample\n")
    L.append("> **POST HOC.** Everything in this report is a post-hoc analysis (prereg/DEVIATIONS.md **D23**). DCv21b "
             "was designed after the pre-registered H15 test had been evaluated (`results/v3/e11_d7/E11_D7_REPORT.md`: "
             "**H15 not supported**), and the defect it repairs was identified from the H15 data. The pre-registered "
             "H15 result is unchanged and stands as reported; nothing here replaces or re-tests it. The margin "
             "−0.02 is borrowed from H15 for comparability only.\n")
    L.append("Generated by `scripts/e11/d7/run_all_d7b.sh` (DCv21b LLM calls cached in `results/v3/e11_d7b/cache/`). "
             "Data: DCv21b episodes `runs/d7/test/X2B/<model>.jsonl` (504 = 7 generators × 72, exactly the "
             "(case_id, model, arm) triples of the DCv21 rows of `results/v3/e11_d7/sample.csv`); DC and DCv21 "
             "claims/judgements reused unchanged from `results/v3/e11_d7/` (not re-judged).\n")
    L.append("## Result (post hoc)\n")
    L.append(f"**DCv21b vs DC** (pooled, {bc['n_pairs']} paired episodes per system, {bc['n_cves']} CVE clusters): "
             f"faithfulness DCv21b {f3(bc['faithfulness_DCv21b'])} ({bc['n_claims_DCv21b']} claims) vs DC "
             f"{f3(bc['faithfulness_DC'])} ({bc['n_claims_DC']} claims); DCv21b − DC = **{bc['diff']:+.3f}** "
             f"(95% paired CVE-clustered bootstrap CI [{bc['lo']:+.3f}, {bc['hi']:+.3f}]; sign-flip p = "
             f"{bc['p_signflip']:.4f}). Lower bound {bc['lo']:+.3f} {'>' if ni else '≤'} −0.02, i.e. by the H15 "
             f"criterion DCv21b would {'' if ni else 'NOT '}be non-inferior to DC (post hoc; not a confirmatory "
             "test).\n")
    L.append(f"**DCv21b vs DCv21** (same triples): {f3(bv['faithfulness_DCv21b'])} vs {f3(bv['faithfulness_DCv21'])}; "
             f"diff **{bv['diff']:+.3f}** [{bv['lo']:+.3f}, {bv['hi']:+.3f}], p = {bv['p_signflip']:.4f}.\n")
    c1 = pr.loc[f"{SYSTEM_B}>DC|pooled|consistent"]
    c2 = pr.loc[f"{SYSTEM_B}>DCv21|pooled|consistent"]
    cv1 = pr.loc[f"{SYSTEM_B}>DC|pooled (cited claims)|cite_valid"]
    L.append(f"Explanation–decision consistency (eligible judges read the asserted status from the note alone): "
             f"DCv21b {f3(c1.a)} vs DC {f3(c1.b)} (diff {dci(c1)}, p = {c1.p_signflip:.4f}); vs DCv21 {f3(c2.b)} "
             f"(diff {dci(c2)}, p = {c2.p_signflip:.4f}). Citation validity DCv21b {f3(cv1.a)} vs DC {f3(cv1.b)}; "
             f"hallucination DCv21b {f3(pr.loc[f'{SYSTEM_B}>DC|pooled|hal'].a)} vs DC "
             f"{f3(pr.loc[f'{SYSTEM_B}>DC|pooled|hal'].b)}.\n")
    ncb = nc[(nc.system == SYSTEM_B) & (nc.arm == "ALL")].iloc[0]
    ncv = nc[(nc.system == "DCv21") & (nc.arm == "ALL")].iloc[0]
    rb = rates[(rates.system == SYSTEM_B) & (rates.model == "ALL") & (rates.arm == "ALL")].iloc[0]
    rv = rates[(rates.system == "DCv21") & (rates.model == "ALL") & (rates.arm == "ALL")].iloc[0]
    L.append(f"Prompt defect: non-fixed DCv21b notes containing \"FIXED\": **{pct(ncb.FIXED_word_share_of_nonfixed)}** "
             f"({int(ncb.n_FIXED_word_nonfixed)}/{int(ncb.n_nonfixed)}; DCv21 on the same triples "
             f"{pct(ncv.FIXED_word_share_of_nonfixed)}, {int(ncv.n_FIXED_word_nonfixed)}/{int(ncv.n_nonfixed)}). "
             f"Validated synthesis (all {int(rb.n)} X2B records): first pass {pct(rb.first_pass)}, repaired "
             f"{pct(rb.repaired)}, fallback {pct(rb.fallback)} (DCv21, same triples: {pct(rv.first_pass)} / "
             f"{pct(rv.repaired)} / {pct(rv.fallback)}).\n")
    L.append(f"Reproduction check: DCv21 − DC recomputed by this pipeline from the reused judgements = "
             f"{vc['diff']:+.3f} [{vc['lo']:+.3f}, {vc['hi']:+.3f}], p = {vc['p_signflip']:.4f} — "
             f"{'identical to' if R['h15_reproduced'] else 'DIFFERENT FROM'} `results/v3/e11_d7/h15.json`.\n")

    L.append("## DCv21b − DC (paired on case × model × arm; post hoc)\n")
    L.append(contrast_table(h, SYSTEM_B, "DC") + "\n")
    L.append("## DCv21b − DCv21 (paired on case × model × arm; post hoc)\n")
    L.append(contrast_table(h, SYSTEM_B, "DCv21") + "\n")
    L.append("CIs: CVE-clustered percentile bootstrap (2,000 resamples, seed 0), the same CVE clusters resampled for "
             "both systems; p: CVE-clustered sign-flip (system labels swapped within a CVE with prob. ½, 10,000 "
             "draws, seed 0) — `d06_metrics.paired_diff` unchanged. No multiplicity correction; all rows are "
             "exploratory. For DCv21b − DCv21 both systems are judged on tool outputs only (neither synthesis prompt "
             "saw the controller `[state]`); the `[state]` row judges both with it.\n")
    L.append("Per validated judge (faithfulness difference, claims for which the judge is eligible):\n")
    rows = [{"comparison": f"{r.system_a} − {r.system_b}", "judge": r.judge, "a": f3(r.a), "b": f3(r.b),
             "diff [95% CI]": dci(r), "p": f"{r.p_signflip:.4f}", "n_a": r.n_a, "n_b": r.n_b}
            for _, r in hj.iterrows()]
    L.append(md(pd.DataFrame(rows)) + "\n")

    L.append("## Metrics per system × arm (504 triples present for all three systems; pooled over generators)\n")
    rows = []
    for t in (sa, ss.assign(arm="ALL")):
        for _, r in t.iterrows():
            rows.append({"system": r.system, "arm": r.arm, "episodes": int(r.n_episodes), "claims": int(r.n_claims),
                         "faithfulness": f"{f3(r.faithfulness)} [{f3(r.faithfulness_lo)}, {f3(r.faithfulness_hi)}]",
                         "hallucination": f3(r.hallucination), "contradicted": f3(r.contradicted),
                         "not_in_ev.": f3(r.not_in_evidence),
                         "consistency": f"{f3(r.consistency)} [{f3(r.consistency_lo)}, {f3(r.consistency_hi)}]",
                         "citation validity": f3(r.get("citation_validity")),
                         "faithf. alt [state]": f3(r.get("faithfulness_alt_state")),
                         "fallback": pct(r.share_fallback) if r.system != "DC" else "n/a",
                         "chars": f"{r.chars_mean:.0f}", "claims/ep": f"{r.claims_per_episode:.2f}"})
    L.append(md(pd.DataFrame(rows)) + "\n")
    L.append("`faithf. alt [state]`: DC judged without its `[state]`; DCv21 / DCv21b judged with it.\n")

    L.append("## Explanation–decision consistency: how judges read the status of the notes (post hoc)\n")
    rows = []
    for sysname in ("DC", "DCv21", SYSTEM_B):
        for dec in ("affected", "not_affected", "fixed", "under_investigation"):
            d = sr[(sr.system == sysname) & (sr.decided == dec)]
            if not len(d):
                continue
            g = d.set_index("read").share
            rows.append({"system": sysname, "decided status": dec, "n readings": int(d.n.sum()),
                         **{f"read {x}": pct(g.get(x, 0.0)) for x in ("affected", "not_affected", "fixed",
                                                                         "under_investigation", "none")}})
    L.append(md(pd.DataFrame(rows)) + "\n")

    L.append("## DCv21b faithfulness by validated-synthesis outcome (sampled DCv21b notes)\n")
    vo2 = vo.copy()
    vo2["arm"] = vo2["arm"].fillna("ALL")
    rows = [{"arm": r.arm, "vs_outcome": r.vs_outcome, "n_episodes": int(r.n_episodes), "n_claims": int(r.n_claims),
             "faithfulness": f"{f3(r.faithfulness)} [{f3(r.faithfulness_lo)}, {f3(r.faithfulness_hi)}]",
             "consistency": f3(r.get("consistency")), "citation_validity": f3(r.get("citation_validity")),
             "chars": f"{r.chars_mean:.0f}"} for _, r in vo2.iterrows()]
    L.append(md(pd.DataFrame(rows)) + "\n")

    L.append("## Validated synthesis: first-pass / repaired / fallback (ALL X2B records = the 504 sampled triples)\n")
    L.append("From the trace entry `validated_synthesis` of every record (none missing). first_pass = validator passed "
             "on attempt 1; repaired = attempt 1 failed, the one repair passed; fallback = both failed, deterministic "
             "note. DCv21b uses the strict validator (additionally rejects notes asserting another status), so its "
             "acceptance bar is higher than DCv21's. DCv21 rows: the same 504 triples from `runs/d7/test/X2`.\n")
    r2 = rates.copy()
    for c in ("missing", "first_pass", "repaired", "fallback", "repair_success_given_fail"):
        r2[c] = r2[c].map(pct)
    r2 = r2[["system", "model", "arm", "n", "first_pass", "repaired", "fallback", "repair_success_given_fail"]]
    L.append(md(r2[(r2.model == "ALL") | (r2.arm == "ALL")]) + "\n")
    L.append("Per model × arm: `v21b_synthesis_rates.csv`.\n")
    L.append("Validator error messages (counts; a note can have several):\n")
    L.append(md(et) + "\n")

    L.append("## Deterministic note checks on the same 504 triples (all three systems)\n")
    L.append("`validate_note` re-applied to the final notes with the full tool outputs, non-strict (DCv21) and strict "
             "(DCv21b). `FIXED` = the upper-case word in a note whose decision is not `fixed` (the E11-D7 finding); "
             "`fixed (any case)` also counts legitimate uses such as \"fixed version 1.2.3\".\n")
    rows = [{"system": r.system, "arm": r.arm, "n": int(r.n), "has_citation": pct(r.has_citation),
             "cited_id_exist": pct(r.cited_id_exist_share), "validator_pass": pct(r.validator_pass),
             "strict_validator_pass": pct(r.strict_validator_pass),
             "asserts another status": pct(r.other_status_asserted),
             "FIXED (non-fixed decisions)": f"{pct(r.FIXED_word_share_of_nonfixed)} ({int(r.n_FIXED_word_nonfixed)}/{int(r.n_nonfixed)})",
             "fixed any case (non-fixed)": pct(r.fixed_anycase_share_of_nonfixed), "chars": f"{r.chars:.0f}"}
            for _, r in nc.iterrows()]
    L.append(md(pd.DataFrame(rows)) + "\n")

    L.append("## Per generator × arm (faithfulness)\n")
    p = smm.pivot_table(index=["model", "arm"], columns="system", values="faithfulness").reset_index()
    fb = smm[smm.system == SYSTEM_B].set_index(["model", "arm"]).share_fallback
    rows = [{"model": r.model, "arm": r.arm, "DC": f3(r.DC), "DCv21": f3(r.DCv21), "DCv21b": f3(r.DCv21b),
             "DCv21b − DC": f"{r.DCv21b - r.DC:+.3f}", "DCv21b − DCv21": f"{r.DCv21b - r.DCv21:+.3f}",
             "DCv21b fallback": pct(fb.get((r.model, r.arm), np.nan))} for _, r in p.iterrows()]
    L.append(md(pd.DataFrame(rows)) + "\n")

    L.append("## Pipeline, replay, judging\n")
    m = ea.merge(eb, on=["case_id", "model", "arm"], suffixes=("_a", "_b"))
    m = m[m.system_a == "DCv21"]
    same_status = (m.status_a == m.status_b).mean()
    L.append(f"- Same pipeline as E11-D7 (`run_all_d7.sh`): `d02` replay/extraction (via `common_d7.EpisodeView`, "
             f"`judge.d7.replay_d7`, same extractor assignment/prompt/schema), `d03` judging (same three E11-validated "
             f"judges {', '.join(VALIDATED)}; nemotron with the `detailed thinking off` system prefix; same family "
             "exclusion; DCv21b like DCv21 judged on tool outputs only in the primary condition), `d06` metric and "
             "test functions imported unchanged. Judge concurrency ≤ 16 per server. The judge-transfer perturbation "
             "check (d04) was not repeated.")
    L.append(f"- Decisions: DCv21b's submitted status equals DCv21's on {pct(same_status)} of the {len(m)} triples "
             f"({int((m.status_a != m.status_b).sum())} differ; same controller, only the note-writing step "
             "differs; pairing is on the triple, not on the decision).")
    L.append(f"- Evidence replay (D7 HostEnv as in `runner.run_episode`): {rp['episodes']} X2B episodes replayed, "
             f"{rp['prefix_mismatch_episodes']} mismatches against the recorded 400-char `out` prefix / id / status, "
             f"{rp['full_trace_mismatch_episodes']} against the full outputs in `trace`; records with errors: "
             f"{rp['records_with_error']}.")
    n_ex = int((eb.extract_error.notna()).sum())
    L.append(f"- Claim extraction (DCv21b): {int(eb.n_claims.sum())} claims from {len(eb)} notes; extraction errors "
             f"{n_ex}; no-claim episodes {int((eb.n_claims == 0).sum())}.")
    jstat = "; ".join(f"{mode} {len(g)} (errors {int(g.error.notna().sum())})" for mode, g in jd.groupby("mode"))
    L.append(f"- DCv21b judge calls by mode: {jstat}; status calls {len(sj)} (errors {int(sj.error.notna().sum())}). "
             "DC/DCv21: cached E11-D7 judgements reused (0 new calls).")
    main_ = jd[(jd["mode"] == "main") & jd.label.notna()]
    piv = main_.pivot_table(index="cid", columns="judge", values="label", aggfunc="first").dropna()
    if len(piv):
        cats = ["supported", "contradicted", "not_in_evidence"]
        counts = [[int((row == c).sum()) for c in cats] for _, row in piv.iterrows()]
        countsb = [[int((row == "supported").sum()), int((row != "supported").sum())] for _, row in piv.iterrows()]
        L.append(f"- Inter-judge agreement on DCv21b claims (all 3 judges, incl. same-family labels; {len(piv)} "
                 f"claims): Fleiss κ 3-class {fleiss_kappa(counts):.3f}, binary {fleiss_kappa(countsb):.3f}; "
                 f"unanimous {pct(float(np.mean([max(c) == 3 for c in counts])))}.")
    L.append(f"- Claims without an eligible validated judge: {R['claims_without_eligible_validated_judge']}.\n")

    L.append("## Caveats\n")
    L.append("1. Post hoc: DCv21b, its validator check and this comparison were specified after the H15 result and "
             "the FIXED finding were known (D23). The H15 margin and test are reused, but the comparison is "
             "exploratory and carries no confirmatory weight; no multiplicity correction is applied.")
    L.append("2. Same sample: DCv21b was run on exactly the H15 triples (and evaluated with the same judges), so the "
             "result is not an independent replication; it isolates the effect of the synthesis-prompt change on "
             "these episodes.")
    n_sc = int(et[(et.system == SYSTEM_B) & (et.attempt == "attempt1")
                  & (et.error_type == "status_conflict_other_status")].n.sum())
    L.append("3. DCv21b's strict validator rejects notes asserting another status, so part of any consistency gain "
             "could be by construction (such notes are repaired or replaced by the deterministic fallback). In these "
             f"records the strict check fired on attempt 1 for only {n_sc} of {int(rb.n)} notes, so the change is "
             "almost entirely due to the neutral prompt wording; judge-based consistency is reported regardless.")
    L.append("4. Generation and judging are at temperature 0; the D7 world physics and episodes are those sealed "
             "under prereg-v3. DC/DCv21 numbers are numerically identical to E11-D7 (reproduction check above).")
    (OUT_B / "E11_D7B_REPORT.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", OUT_B / "E11_D7B_REPORT.md")


if __name__ == "__main__":
    main()
