"""E11-D7 step 8: write results/v3/e11_d7/E11_D7_REPORT.md from the CSV/JSON outputs."""

from __future__ import annotations

import json

import numpy as np
import pandas as pd
from common_d7 import OUT, VALIDATED, read_jsonl


def f3(x) -> str:
    return "–" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.3f}"


def pct(x) -> str:
    return "–" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{100 * x:.1f}%"


def ci(r, k) -> str:
    return f"{f3(r[k])} [{f3(r[k + '_lo'])}, {f3(r[k + '_hi'])}]" if f"{k}_lo" in r else f3(r[k])


def md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for r in df.itertuples(index=False):
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def main() -> None:
    h = json.loads((OUT / "h15.json").read_text())
    ht = pd.read_csv(OUT / "h15_test.csv")
    hj = pd.read_csv(OUT / "h15_per_judge.csv")
    sa = pd.read_csv(OUT / "metrics_system_arm.csv")
    ss = pd.read_csv(OUT / "metrics_system.csv")
    smm = pd.read_csv(OUT / "metrics_system_model_arm.csv")
    vo = pd.read_csv(OUT / "metrics_v21_by_outcome.csv")
    rates = pd.read_csv(OUT / "v21_synthesis_rates.csv")
    et = pd.read_csv(OUT / "v21_attempt1_error_types.csv")
    nc = pd.read_csv(OUT / "note_checks_all_records.csv")
    rp = json.loads((OUT / "replay_check_all.json").read_text())
    eps = pd.DataFrame(read_jsonl(OUT / "episodes.jsonl"))
    tv = pd.read_csv(OUT / "transfer_validation.csv") if (OUT / "transfer_validation.csv").exists() else None
    tvt = (pd.read_csv(OUT / "transfer_validation_by_type.csv")
           if (OUT / "transfer_validation_by_type.csv").exists() else None)
    jd = pd.DataFrame(read_jsonl(OUT / "judgments.jsonl"))
    sj = pd.DataFrame(read_jsonl(OUT / "status_judgments.jsonl"))
    holds = h["H15_holds"]
    L = []
    L.append("# E11 on D7 — H15: analyst-note faithfulness of DCv21 (validated synthesis) vs DC (unvalidated)\n")
    L.append("Generated by `scripts/e11/d7/run_all_d7.sh` (all LLM calls cached in `results/v3/e11_d7/cache/`). "
             "Pre-registration: `prereg/PREREGISTRATION_V3.md` §3 (H15, secondary). Protocol: "
             "`results/v3/e11/PROTOCOL.md` (unchanged; D7 adaptations listed below). Data: `runs/d7/test/X2/`, "
             "D7 test labels via `set_dataset('d7'); load_labels('test', allow_sealed=True)`.\n")
    L.append("## Result\n")
    verdict = "**H15 holds**" if holds else "**H15 does not hold**"
    L.append(f"{verdict} (non-inferiority, margin −0.02 on the lower 95% CI bound). Claim faithfulness, pooled over "
             f"7 generators × 3 arms ({h['n_pairs']} paired episodes per system, {h['n_cves']} CVE clusters): "
             f"DCv21 {f3(h['faithfulness_DCv21'])} ({h['n_claims_DCv21']} claims) vs DC {f3(h['faithfulness_DC'])} "
             f"({h['n_claims_DC']} claims); difference DCv21 − DC = **{h['diff']:+.3f}** "
             f"(95% paired CVE-clustered bootstrap CI [{h['lo']:+.3f}, {h['hi']:+.3f}]; CVE-clustered sign-flip "
             f"p = {h['p_signflip']:.4f}, two-sided, H0: no difference). Lower bound {h['lo']:+.3f} "
             f"{'>' if holds else '≤'} −0.02.\n")
    pr = ht.set_index(ht.contrast + "|" + ht.metric)
    cons = pr.loc["pooled|consistent"]
    L.append(f"Secondary: explanation–decision consistency DCv21 {f3(cons.v21)} vs DC {f3(cons.dc)} "
             f"(diff {cons['diff']:+.3f} [{cons.lo:+.3f}, {cons.hi:+.3f}], p = {cons.p_signflip:.4f}); citation "
             f"validity (claims citing call ids) DCv21 {f3(pr.loc['pooled (cited claims)|cite_valid'].v21)} vs DC "
             f"{f3(pr.loc['pooled (cited claims)|cite_valid'].dc)}; hallucination DCv21 {f3(pr.loc['pooled|hal'].v21)} "
             f"vs DC {f3(pr.loc['pooled|hal'].dc)}.\n")
    sn = pr.loc["sens: neither judged with [state] (DC nostate)|x"] if "sens: neither judged with [state] (DC nostate)|x" in pr.index else None
    sb = pr.loc["sens: both judged with [state] (DCv21 + state)|x"] if "sens: both judged with [state] (DCv21 + state)|x" in pr.index else None
    if sn is not None and sb is not None:
        jtxt = "; ".join(f"{r.judge} {r['diff']:+.3f} [{r.lo:+.3f}, {r.hi:+.3f}]" for _, r in hj.iterrows())
        L.append("Reading: the primary difference is not significantly different from 0, but its CI extends below the "
                 "−0.02 margin, so non-inferiority is not shown. The result depends on the evidence condition: with "
                 f"both systems judged on tool outputs only, DCv21 − DC = {sn['diff']:+.3f} [{sn.lo:+.3f}, {sn.hi:+.3f}] "
                 "(DC's notes restate controller-derived facts that the raw outputs alone often do not show); with both "
                 f"judged with the controller `[state]`, {sb['diff']:+.3f} [{sb.lo:+.3f}, {sb.hi:+.3f}]. Per judge: "
                 f"{jtxt}.\n")
    ncv = nc[nc.system == "DCv21"]
    fx = ncv.n_FIXED_word_nonfixed.sum() / ncv.n_nonfixed.sum() if "n_FIXED_word_nonfixed" in ncv else float("nan")
    sjm = sj.merge(eps[["key", "system", "status", "model"]], on="key")
    sjm = sjm[[__import__("deepcti.judge.d7", fromlist=["eligible_d7"]).eligible_d7(j, m)
               for j, m in zip(sjm.judge, sjm.model)]]
    ui = sjm[(sjm.system == "DCv21") & (sjm.status == "under_investigation")]
    ui_dc = sjm[(sjm.system == "DC") & (sjm.status == "under_investigation")]
    L.append("**Finding (validated-synthesis prompt).** The DCv21 synthesis prompt states the decision as "
             "\"The decision is FIXED (do not change it): <status> …\" (`agents/systems.py::_explain_validated`). "
             f"Across all D7 test records, {pct(fx)} of DCv21 notes whose decision is not `fixed` contain the word "
             "\"FIXED\" (DC: 0%), typically \"… is marked as FIXED\". The validator (`validate_note`) only checks that "
             "the decided status word occurs and that an `affected` note does not say \"not affected\", so these notes "
             "pass. Judges reading the note alone take \"fixed\" as the asserted status: for DCv21 notes with decision "
             f"`under_investigation`, {pct((ui.asserted_status == 'fixed').mean())} of eligible-judge status readings are "
             f"`fixed` (DC: {pct((ui_dc.asserted_status == 'fixed').mean())}). This drives the consistency drop "
             "and the lower faithfulness of DCv21 status/conclusion claims (table below); fallback notes (which start "
             "\"Status: <status>\") are fully consistent.\n")
    fb_all = rates[(rates.model == "ALL") & (rates.arm == "ALL")].fallback.iloc[0]
    L.append(f"DCv21 notes that are deterministic fallbacks: {pct(h['share_fallback_DCv21'])} of the sampled DCv21 "
             f"episodes (all-records rate: {pct(fb_all)}). "
             "Fallback notes are evaluated like any other note; results excluding them are below.\n")

    L.append("## H15 test and secondary contrasts (DCv21 − DC, paired on case × model × arm)\n")
    t = ht.copy()
    t["DCv21"] = t.v21.map(f3)
    t["DC"] = t.dc.map(f3)
    t["diff [95% CI]"] = [f"{d:+.3f} [{lo:+.3f}, {hi:+.3f}]" for d, lo, hi in zip(t["diff"], t.lo, t.hi)]
    t["p (sign-flip)"] = t.p_signflip.map(lambda p: f"{p:.4f}")
    t["n claims/eps (v21, DC)"] = [f"{a}, {b}" for a, b in zip(t.n_a, t.n_b)]
    names = {"sup": "faithfulness", "hal": "hallucination", "con": "contradicted", "nie": "not_in_evidence",
             "consistent": "expl–decision consistency", "cite_valid": "citation validity", "x": "faithfulness"}
    t["metric"] = t.metric.map(names)
    L.append(md(t[["contrast", "metric", "DCv21", "DC", "diff [95% CI]", "p (sign-flip)", "n claims/eps (v21, DC)",
                   "cves"]]))
    L.append("\nCIs: CVE-clustered percentile bootstrap (2,000 resamples, seed 0), the same CVE clusters resampled "
             "for both systems; p: CVE-clustered sign-flip (system labels swapped within a CVE with prob. ½, 10,000 "
             "draws, seed 0). Only the first row is the pre-registered H15 test; the rest are secondary.\n")
    L.append("Per validated judge (faithfulness difference, claims for which the judge is eligible):\n")
    hj2 = hj.assign(**{"DCv21": hj.v21.map(f3), "DC": hj.dc.map(f3),
                       "diff [95% CI]": [f"{d:+.3f} [{lo:+.3f}, {hi:+.3f}]" for d, lo, hi in
                                         zip(hj["diff"], hj.lo, hj.hi)], "p": hj.p_signflip.map(lambda p: f"{p:.4f}")})
    L.append(md(hj2[["judge", "DCv21", "DC", "diff [95% CI]", "p", "n_a", "n_b"]]))

    L.append("\n## Metrics per system × arm (paired sample; pooled over generators)\n")
    rows = []
    for d in (sa, ss.assign(arm="ALL")):
        for r in d.to_dict("records"):
            rows.append({"system": r["system"], "arm": r["arm"], "episodes": r["n_episodes"], "claims": r["n_claims"],
                         "faithfulness": ci(r, "faithfulness"), "hallucination": ci(r, "hallucination"),
                         "contradicted": f3(r["contradicted"]), "not_in_ev.": f3(r["not_in_evidence"]),
                         "consistency": ci(r, "consistency"), "consist. coarse": f3(r.get("consistency_coarse")),
                         "citation validity": ci(r, "citation_validity") if "citation_validity" in r else "–",
                         "cited-id exists": f3(r.get("cite_id_exist")), "fallback share": pct(r["share_fallback"])
                         if r["system"] == "DCv21" else "n/a", "chars": f"{r['chars_mean']:.0f}",
                         "claims/ep": f"{r['claims_per_episode']:.2f}"})
    L.append(md(pd.DataFrame(rows)))
    L.append("\nFaithfulness = Σ soft(supported)/#claims; soft label = share of eligible validated judges "
             f"({', '.join(VALIDATED)}; never the generator's own family) giving the label. Hallucination = "
             "contradicted + not_in_evidence. Consistency = share of eligible judges whose asserted status (from the "
             "note alone) equals the submitted status. Citation validity: claims citing ≥ 1 call id; valid = all "
             "cited ids exist and the claim is supported by the cited outputs alone. Evidence: replayed tool "
             "outputs (3,000-char cap); DC additionally its controller `[state]` (E11 primary). The alternative "
             "evidence condition (DC without `[state]`, DCv21 with `[state]`) is in `metrics_system_arm.csv` "
             "(`faithfulness_alt_state`).\n")

    L.append("## DCv21 faithfulness by validated-synthesis outcome (sampled DCv21 notes)\n")
    v = vo.copy()
    v["arm"] = v["arm"].fillna("ALL")
    v = v[["arm", "vs_outcome", "n_episodes", "n_claims", "faithfulness", "faithfulness_lo", "faithfulness_hi",
           "hallucination", "consistency", "citation_validity", "chars_mean"]].sort_values(["arm", "vs_outcome"])
    v["faithfulness"] = [f"{a:.3f} [{b:.3f}, {c:.3f}]" for a, b, c in zip(v.faithfulness, v.faithfulness_lo,
                                                                       v.faithfulness_hi)]
    for c in ("hallucination", "consistency", "citation_validity"):
        v[c] = v[c].map(f3)
    v["chars_mean"] = v.chars_mean.map(lambda x: f"{x:.0f}")
    L.append(md(v.drop(columns=["faithfulness_lo", "faithfulness_hi"])))

    L.append("\n## Validated synthesis: first-pass / repaired / fallback rates (ALL D7 test DCv21 records)\n")
    L.append("From the trace entry `{\"validated_synthesis\": {attempt1_errors, repaired, fallback, attempt2_errors}}` "
             "of every DCv21 record (7 models × 3 arms × 414 cases = 8,694 notes; no record lacks the entry). "
             "first_pass = validator passed on attempt 1; repaired = attempt 1 failed, the one repair passed; "
             "fallback = both failed, deterministic note emitted.\n")
    r2 = rates.copy()
    for c in ("first_pass", "repaired", "fallback", "attempt1_fail", "repair_success_given_fail"):
        r2[c] = r2[c].map(pct)
    piv = r2[(r2.model != "ALL") & (r2.arm != "ALL")]
    L.append(md(piv[["model", "arm", "n", "first_pass", "repaired", "fallback", "repair_success_given_fail"]]))
    L.append("")
    L.append(md(r2[(r2.model == "ALL") | (r2.arm == "ALL")][["model", "arm", "n", "first_pass", "repaired", "fallback",
                                                            "repair_success_given_fail"]]))
    sm = eps[eps.system == "DCv21"].vs_outcome.value_counts()
    L.append(f"\nIn the judged sample (n = {int(sm.sum())} DCv21 notes): " +
             ", ".join(f"{k} {v} ({pct(v / sm.sum())})" for k, v in sm.items()) + ".\n")
    e1 = et.groupby(["attempt", "error_type"]).n.sum().reset_index()
    L.append("Validator error messages (counts over all records; a note can have several):\n")
    L.append(md(e1))
    L.append("\nDeterministic note checks on ALL records (the DCv21 validator `validate_note` re-applied to both "
             "systems' final notes with full tool outputs):\n")
    nc2 = nc.copy()
    for c in ("empty", "has_citation", "validator_pass", "cited_id_exist_share"):
        nc2[c] = nc2[c].map(pct)
    nc2["chars"] = nc2.chars.map(lambda x: f"{x:.0f}")
    if "FIXED_word_share_of_nonfixed" in nc2:
        nc2["FIXED word (non-fixed decisions)"] = nc2.FIXED_word_share_of_nonfixed.map(pct)
    L.append(md(nc2[[c for c in ["system", "arm", "n", "has_citation", "cited_id_exist_share", "validator_pass",
                                 "FIXED word (non-fixed decisions)", "chars"] if c in nc2]]))

    L.append("\n## Per generator × arm (faithfulness; paired sample)\n")
    p = smm.pivot_table(index=["model", "arm"], columns="system", values="faithfulness").reset_index()
    p["diff"] = p["DCv21"] - p["DC"]
    nfb = smm[smm.system == "DCv21"].set_index(["model", "arm"]).share_fallback
    p["DCv21 fallback share"] = [pct(nfb.get((m, a))) for m, a in zip(p.model, p.arm)]
    for c in ("DC", "DCv21"):
        p[c] = p[c].map(f3)
    p["diff"] = p["diff"].map(lambda x: f"{x:+.3f}")
    L.append(md(p))

    L.append("\n## Sample, evidence replay, judging\n")
    L.append(f"- Sample (`d01_sample.py`, seed 20261005): 168 distinct D7 test cases drawn stratified by ecosystem × "
             "variant (proportional, largest remainder), shuffled and split into 7 blocks of 24, block k → generator k "
             "(gemma4_31b, granite41_30b, granite41_8b, llama31_8b, mistral_small_24b, qwen3_14b, qwen3_4b). For each "
             f"(generator, case): DC and DCv21 × tracker/withheld/blind = {len(eps)} episodes, 168 per system × arm, "
             f"{eps.cve.nunique()} CVEs. Episodes with errors: {int(eps.error.sum())}. Pairs used: {h['n_pairs']} "
             f"({h['n_pairs_per_arm']}).")
    L.append(f"- Evidence replay (D7 HostEnv as in `runner.run_episode` with dataset d7: per-ecosystem v3 trust "
             f"profiles, `env.spec_version='v3'`): sampled episodes with a replay mismatch: "
             f"{int((eps.replay_mismatch.map(len) > 0).sum())}. Full check over ALL {rp['episodes']} D7 test DC/DCv21 "
             f"episodes: {rp['prefix_mismatch_episodes']} mismatches against the recorded 400-char `out` prefix / id / "
             f"status, {rp['full_trace_mismatch_episodes']} mismatches against the full outputs in `trace`.")
    ncl = eps.groupby("system").n_claims.agg(["sum", "mean"])
    L.append(f"- Claim extraction (extractor gemma_4_31b; granite_41_30b for gemma4_31b episodes): "
             f"{int(ncl['sum'].sum())} claims (DC {int(ncl.loc['DC', 'sum'])}, DCv21 {int(ncl.loc['DCv21', 'sum'])}); "
             f"extraction errors {int(eps.extract_error.notna().sum())}; no-claim episodes "
             f"{int((eps.n_claims == 0).sum())}.")
    if len(jd):
        jerr = jd.groupby("mode").agg(n=("label", "size"), errors=("error", lambda s: int(s.notna().sum())))
        L.append("- Judge calls by mode: " + ", ".join(f"{m} {r.n} (errors {r.errors})" for m, r in jerr.iterrows())
                 + f"; status calls {len(sj)} (errors {int(sj.error.notna().sum())}).")
        main = jd[(jd["mode"] == "main") & jd.label.notna()].pivot_table(index="cid", columns="judge", values="label",
                                                                       aggfunc="first").dropna()
        if len(main):
            from deepcti.judge.stats import fleiss_kappa
            cats = ["supported", "contradicted", "not_in_evidence"]
            counts = [[sum(r[j] == c for j in main.columns) for c in cats] for _, r in main.iterrows()]
            countsb = [[sum(r[j] == "supported" for j in main.columns),
                        sum(r[j] != "supported" for j in main.columns)] for _, r in main.iterrows()]
            L.append(f"- Inter-judge agreement on D7 claims (all {len(main.columns)} validated judges, incl. same-family "
                     f"labels used for agreement only; {len(main)} claims): Fleiss κ 3-class "
                     f"{fleiss_kappa(counts):.3f}, binary {fleiss_kappa(countsb):.3f}; unanimous "
                     f"{pct(np.mean([max(c) == len(main.columns) for c in counts]))}.")
    if tv is not None:
        L.append("\n## Judge-validation transfer check on D7 (secondary; does not change the judge set)\n")
        L.append("The E11 perturbation test (same edit code, `perturb.py`) on D7 DC/DCv21 claims labelled supported by "
                 "all three validated judges: 40 items per edit type, 80 untouched controls, leave-one-out reference "
                 "(the other two judges label the base claim supported).\n")
        tv2 = tv.copy()
        tv2["recall"] = tv2.recall.map(f3)
        tv2["false_alarm"] = tv2.false_alarm.map(f3)
        L.append(md(tv2))
        if tvt is not None:
            L.append("")
            L.append(md(tvt.pivot_table(index="judge", columns="kind", values="rate").round(3).reset_index()))
    L.append("\n## Deviations / adaptations from PROTOCOL.md (1–5 fixed before any judge label was seen; 6 post hoc)\n")
    L.append("1. Data and systems: D7 test (`runs/d7/test/X2`), systems DC and DCv21, arms tracker/withheld/blind, "
             "7 generators (granite41_30b added to the generator→family map: granite; judges of the generator's family "
             "are never used for system-level quantities). Sample: 168 cases (24 per generator), stratified by "
             "ecosystem × variant instead of variant only (D7 has four ecosystems).")
    L.append("2. Judges: only the three judges that PASSED E11 validation (gemma_4_31b, nemotron_super_49b with the "
             "`detailed thinking off` system prefix, granite_41_30b) are run; mistral_small_24b and qwen3_14b (failed "
             "validation) are not queried. Every validated judge labels every claim in main mode (agreement); cited / "
             "status / sensitivity modes are run for eligible judges only. Concurrency ≤ 16 per server.")
    L.append("3. Episode context block: the E11 template says \"(Debian <release>)\" and \"source package\"; for D7 it "
             "states the distro/release, ecosystem and advisory component, and, in the blind arm, that scanners were "
             "not available (`deepcti.judge.d7.context_block_d7`). Judge/extractor/status prompts and schemas are "
             "unchanged (their status definitions are worded for Debian packages; this applies equally to both systems).")
    L.append("4. Evidence: DC is judged with the replayed tool outputs + its controller `[state]` (E11 primary). "
             "DCv21's synthesis prompt never received the state (it received the raw cited outputs), so per the E11 "
             "rule (evidence = what the system's response LLM was given) its primary evidence is the tool outputs "
             "alone. Both symmetric alternatives are reported (neither with `[state]`; both with `[state]`).")
    L.append("5. H15 primary test pools all arms and generators (the pre-registration states no arm); per-arm and "
             "per-generator differences are secondary. The sign-flip p-value is a CVE-clustered label-swap test of "
             "the ratio difference (`deepcti.judge.paired.signflip_ratio_diff`). No-claim episodes contribute no "
             "claims (as E11).")
    L.append("6. Post hoc (added after the consistency result was seen; secondary, labelled as such): the \"FIXED\" "
             "word count in DCv21 notes (`note_checks_all_records.csv`) and the status-reading breakdown in the Finding "
             "paragraph; the status/conclusion vs factual-detail split (as E11 deviation 3); the judge-transfer "
             "perturbation check (its pool and controls are claims all three judges labelled supported, so it checks "
             "sensitivity to injected errors, not agreement with an independent reference).")
    (OUT / "E11_D7_REPORT.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", OUT / "E11_D7_REPORT.md")


if __name__ == "__main__":
    main()
