"""E0 analysis (Paper 2): where agents' questions go, critical omissions, and their link to dangerous errors.

Reads results/inquiry/e0/{episodes,calls}.csv.gz (scripts/inquiry/audit_e0.py). Writes:
  results/inquiry/e0/E0_REPORT.md, results/inquiry/e0/tables/*.csv, results/inquiry/e0/e0_long.csv (for the GLMM),
  paper2/figs/fig_e0_questions.{pdf,png}
Primary measures are label-derived (category of each question, critical omissions); there is no model-based VOI here.

  .venv/bin/python scripts/inquiry/analyze_e0.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "paper"))
E0 = ROOT / "results" / "inquiry" / "e0"
TAB = E0 / "tables"
FIG = ROOT / "paper2" / "figs"
SIZE = {"qwen3_4b": 4, "llama31_8b": 8, "granite41_8b": 8, "qwen3_14b": 14, "mistral_small_24b": 24,
        "granite41_30b": 30, "gemma4_31b": 31, "nemotron_super_49b": 49, "mistral_medium_128b": 128,
        "glm45_air": 106}
AGENTS = ["S3", "S4", "S5", "S3I"]          # LLM agents that choose their own questions
CONTROLLERS = ["DC", "DCv21", "DCv21b", "DCt", "S1p", "DC_checklist", "DC_entropy", "DC_llmchoose", "DC_random",
               "DC_noverify", "DC_k1", "DC_nofresh", "DC_q2"]
CATS = ["relevant", "redundant", "irrelevant", "misleading"]
BLOCK_PRIORITY = ["E2", "E4", "X4", "E9", "E10", "ABL", "E3", "X2", "X5", "X6", "X7", "X2B", "X2C", "X2I", "X3",
                  "X6C", "X2V"]


def boot_rate(df: pd.DataFrame, col: str, n: int = 2000, seed: int = 7) -> tuple[float, float, float]:
    """CVE-clustered percentile bootstrap of a mean."""
    per = df.groupby("cve")[col].agg(["sum", "size"])
    s, c = per["sum"].to_numpy(float), per["size"].to_numpy(float)
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(per), size=(n, len(per)))
    boots = s[idx].sum(1) / c[idx].sum(1)
    return float(s.sum() / c.sum()), float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))


def fmt(t: tuple[float, float, float], pct: bool = True) -> str:
    m = 100 if pct else 1
    return f"{t[0] * m:.1f} [{t[1] * m:.1f}, {t[2] * m:.1f}]" if pct else f"{t[0]:.3f} [{t[1]:.3f}, {t[2]:.3f}]"


def main() -> None:
    TAB.mkdir(parents=True, exist_ok=True)
    FIG.mkdir(parents=True, exist_ok=True)
    ep = pd.read_csv(E0 / "episodes.csv.gz")
    calls = pd.read_csv(E0 / "calls.csv.gz", usecols=["key", "source_file", "tool", "category"])
    # One record per episode key: some blocks re-run identical specs (X2V = post-hoc verifier re-run of X2's
    # vendor cases; X6C = clean control re-running X2 cells; X3/E3 budget-60 cells = X2/E2 cells). Keep the
    # record from the original main block so no episode is counted twice.
    ep["block"] = ep["source_file"].str.extract(r"/([^/]+)/[^/]+\.jsonl$")[0]
    n_all = len(ep)
    ep["prio"] = ep["block"].map({b: i for i, b in enumerate(BLOCK_PRIORITY)}).fillna(len(BLOCK_PRIORITY))
    ep = ep.sort_values(["prio", "source_file"]).drop_duplicates("key", keep="first").drop(columns="prio")
    calls = calls.merge(ep[["key", "source_file"]], on=["key", "source_file"])
    test = ep[ep["split"].fillna("test") == "test"].copy()
    test["family"] = np.where(test["system"].isin(AGENTS), "agent",
                              np.where(test["system"].isin(CONTROLLERS), "controller", "other"))
    test["omission"] = test["omission_2step"].astype(bool)
    test["omission1"] = test["omission_1step"].astype(bool)
    q = test["n_questions"].clip(lower=1)
    test["wasted_share"] = (test["n_redundant"] + test["n_irrelevant"]) / q
    test["affected"] = test["gold_label"] == "affected"
    test["setting"] = np.where(test["drift"].fillna("") != "", "drift",
                               np.where(test["decoy"].astype(bool), "decoy", "clean"))
    md = ["# E0 — retrospective question audit (Paper 2, Phase 1)", "",
          "Generated by `scripts/inquiry/analyze_e0.py` from `results/inquiry/e0/` (`scripts/inquiry/audit_e0.py`).",
          "Paper 1 run logs re-scored at question level; no new LLM calls. Test split unless stated; attack blocks",
          "(E5, KM) excluded. Definitions: `src/deepcti/inquiry/audit.py` (module docstring). CIs: CVE-clustered",
          "bootstrap (2,000 resamples).", ""]
    meta = (E0 / "run_meta.json").read_text()
    md += ["## Inputs", "", "```json", meta.strip(), "```", "",
           f"Deduplicated to one record per episode key (original block preferred): {n_all:,} → {len(ep):,} episodes"
           f" ({len(test):,} test).", ""]

    # 1. where the questions go
    c = calls.merge(test[["key", "source_file", "system", "dataset", "arm"]], on=["key", "source_file"])
    pre = c[c["category"] != "post_decision"]
    share = pre.groupby(["dataset", "system"])["category"].value_counts(normalize=True).unstack(fill_value=0)
    share = share.reindex(columns=CATS, fill_value=0)
    nq = test.groupby(["dataset", "system"])["n_questions"].mean().rename("questions_per_episode")
    t1 = share.join(nq).round(3)
    t1.to_csv(TAB / "question_categories.csv")
    md += ["## 1. Where the questions go (share of pre-decision questions)", "",
           "relevant = adds a decision-useful evidence component; redundant = repeats an earlier call or output;",
           "irrelevant = neither; misleading = makes face-value inference about a required atom wrong.", "",
           t1.to_markdown(), ""]

    # 2. critical omissions
    rows = []
    for (ds, setting, arm, sysn), g in test.groupby(["dataset", "setting", "arm", "system"]):
        if len(g) < 30:
            continue
        rows.append({"dataset": ds, "setting": setting, "arm": arm, "system": sysn, "n": len(g),
                     "omission_1step_%": round(100 * g["omission1"].mean(), 1),
                     "omission_2step_%": round(100 * g["omission"].mean(), 1),
                     "unestablished_at_decision_%": round(100 * (g["missing_at_decision"].fillna("") != "").mean(), 1),
                     "DER": round(g[g["affected"]]["dangerous"].mean(), 3) if g["affected"].any() else np.nan})
    t2 = pd.DataFrame(rows)
    t2.to_csv(TAB / "omissions_by_system.csv", index=False)
    md += ["## 2. Critical omissions by system", "",
           "Critical omission: at decision time a required atom is not established although ≤ 1 (1-step) or ≤ 2",
           "(2-step) affordable catalog questions would have established it.", "", t2.to_markdown(index=False), ""]

    # 3. omission vs dangerous error (affected-gold episodes)
    rows = []
    for fam_name, sysset in (("LLM agents (S3, S4, S5, S3I)", AGENTS), ("S3 ReAct", ["S3"]),
                             ("DC (v2.0)", ["DC"]), ("all systems", None)):
        g = test[test["affected"] & (test["system"].isin(sysset) if sysset else True)]
        if g.empty:
            continue
        de = g[g["dangerous"].astype(bool)]
        rows.append({"systems": fam_name, "affected_episodes": len(g), "dangerous": len(de),
                     "DER_with_omission": fmt(boot_rate(g[g["omission"]].assign(x=lambda d: d["dangerous"].astype(float)), "x"))
                     if g["omission"].any() else "",
                     "DER_without_omission": fmt(boot_rate(g[~g["omission"]].assign(x=lambda d: d["dangerous"].astype(float)), "x"))
                     if (~g["omission"]).any() else "",
                     "misses_preceded_by_omission_%": fmt(boot_rate(de.assign(x=de["omission"].astype(float)), "x"))
                     if len(de) else ""})
    t3 = pd.DataFrame(rows)
    t3.to_csv(TAB / "omission_vs_der.csv", index=False)
    md += ["## 3. Omissions and dangerous errors (gold = affected)", "", t3.to_markdown(index=False), ""]

    # 3b. decomposition of LLM-agent misses by information status at decision time
    de = test[test["affected"] & test["dangerous"].astype(bool) & test["system"].isin(AGENTS)].copy()
    miss = de["missing_at_decision"].fillna("")
    de["cause"] = np.where(de["omission"], "omission: decision-critical fact askable but not asked",
                           np.where(miss == "", "facts established, wrong decision",
                                    "facts unobtainable within catalog and budget"))
    t3b = (de.groupby("dataset")["cause"].value_counts(normalize=True).unstack(fill_value=0).round(3)
           .assign(misses=de.groupby("dataset").size()))
    pooled = de["cause"].value_counts(normalize=True).round(3).rename("pooled")
    t3b.to_csv(TAB / "miss_decomposition.csv")
    md += ["### 3b. What preceded each LLM-agent miss", "", t3b.to_markdown(), "",
           "Pooled: " + "; ".join(f"{k} {v:.1%}" for k, v in pooled.items()), ""]

    # 4. sanity: process-view omission in D2 upgrade-without-restart DC episodes
    d2 = test[(test["dataset"] == "d1") & test["drift"].fillna("").str.contains("upgrade_no_restart")]
    rows = []
    for sysn, g in d2.groupby("system"):
        rows.append({"system": sysn, "n": len(g), "omission_%": round(100 * g["omission"].mean(), 1),
                     "fixer_includes_service_status_%":
                         round(100 * g["omission_fixers"].fillna("").str.contains("service_status").mean(), 1),
                     "accuracy": round(g["correct"].mean(), 3)})
    t4 = pd.DataFrame(rows)
    t4.to_csv(TAB / "sanity_d2_upgrade_no_restart.csv", index=False)
    md += ["## 4. Sanity check: D2 upgrade without restart (expected: DC omits the process view ~100%)", "",
           t4.to_markdown(index=False), ""]

    # 5. model size: omissions vs wasted questions (S3)
    s3 = test[test["system"] == "S3"]
    t5 = s3.groupby(["dataset", "model"]).agg(n=("key", "size"), omission=("omission", "mean"),
                                              wasted_share=("wasted_share", "mean"),
                                              questions=("n_questions", "mean"),
                                              DER=("dangerous", lambda x: x[s3.loc[x.index, "affected"]].mean())
                                              ).round(3).reset_index()
    t5["size_b"] = t5["model"].map(SIZE)
    t5 = t5.sort_values(["dataset", "size_b"])
    t5.to_csv(TAB / "s3_by_model.csv", index=False)
    corr = []
    for ds, g in t5.groupby("dataset"):
        g = g.dropna(subset=["size_b"])
        if len(g) >= 4:
            ls = np.log(g["size_b"])
            corr.append(f"- {ds.upper()}: Spearman ρ(log size, omission) = {g['omission'].corr(ls, method='spearman'):.2f}; "
                        f"ρ(log size, wasted share) = {g['wasted_share'].corr(ls, method='spearman'):.2f} "
                        f"({len(g)} models; descriptive)")
    md += ["## 5. ReAct (S3) by model: omissions vs wasted questions", "", t5.to_markdown(index=False), "", *corr, ""]

    # long table for the GLMM
    long = test[test["affected"] & test["system"].isin(AGENTS)][
        ["key", "system", "model", "cve", "dataset", "arm", "dangerous", "omission", "wasted_share", "n_questions"]]
    long.to_csv(E0 / "e0_long.csv", index=False)
    md += ["## 6. Mixed model", "", "`.renv/bin/Rscript scripts/inquiry/e0_glmm.R` → `results/inquiry/e0/glmm.md`:",
           "dangerous ~ omission + wasted_share + model + dataset + (1 | cve), LLM agents, gold = affected.", ""]
    (E0 / "E0_REPORT.md").write_text("\n".join(md) + "\n")
    figure(test, pre)
    print("\n".join(md))


def figure(test: pd.DataFrame, pre: pd.DataFrame) -> None:
    import matplotlib.pyplot as plt
    from figures import INK2, SURF, grid, save  # noqa: F401  (paper style)
    import figures as F
    F.OUT = FIG  # write into paper2/figs (not Paper 1's paper/figs)
    order = [("S3", "ReAct (S3)"), ("S4", "ReAct + scratchpad"), ("S5", "ReAct + reflection"), ("S3I", "Inspect ReAct"),
             ("DC", "DeepCTI (EC²)"), ("DC_checklist", "checklist"), ("DC_llmchoose", "LLM-chosen"),
             ("DC_random", "random order")]
    cols = {"relevant": "#2a78d6", "redundant": "#c3c2b7", "irrelevant": "#898781", "misleading": "#e34948"}
    fig, axes = plt.subplots(1, 2, figsize=(F.DOUBLE, 2.1), sharey=True)
    y = np.arange(len(order))
    for ax, ds, title in ((axes[0], "d1", "D1 (Debian)"), (axes[1], "d7", "D7 (4 ecosystems)")):
        p = pre[pre["dataset"] == ds]
        share = p.groupby("system")["category"].value_counts(normalize=True).unstack(fill_value=0)
        om = test[test["dataset"] == ds].groupby("system")["omission"].mean()
        left = np.zeros(len(order))
        for cat in CATS:
            vals = np.array([share.loc[s].get(cat, 0.0) if s in share.index else 0.0 for s, _ in order])
            ax.barh(y, vals, left=left, color=cols[cat], height=0.62, edgecolor=SURF, linewidth=0.8, zorder=2,
                    label=cat if ds == "d1" else None)
            left += vals
        for yi, (s, _) in zip(y, order):
            txt = f"{100 * om[s]:.0f}%" if s in om.index and s in share.index else "not run"
            ax.text(1.02, yi, txt, va="center", fontsize=6, color=INK2, transform=ax.get_yaxis_transform())
        ax.set_xlim(0, 1)
        ax.set_xticks([0, 0.5, 1], ["0%", "50%", "100%"])
        ax.set_title(f"{title}: share of questions", loc="left", fontsize=7)
        ax.text(1.02, -0.85, "omission", fontsize=6, color=INK2, transform=ax.get_yaxis_transform())
        grid(ax)
    axes[0].set_yticks(y, [lab for _, lab in order])
    axes[0].set_ylim(len(order) - 0.5, -1.0)
    fig.legend(frameon=False, fontsize=6, ncol=4, loc="lower center", bbox_to_anchor=(0.5, -0.08))
    save(fig, "fig_e0_questions")


if __name__ == "__main__":
    main()
