"""Policy decision point with epistemic (evidence-conditioned) authorization (plan §3.5 T4, §5.5).

Policies are written in Cedar and evaluated with ``cedarpy``. A pure-Python reference
evaluator implements the same semantics; tests assert both agree. A linter checks that every
permit reachable by a disruptive action lies in the *positive-threshold fragment* required by
Theorem T4: a pure conjunction that contains, for every gating atom f,
``context.atoms.f.val == "T"`` and ``context.atoms.f.kpos >= k_f``.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path

import cedarpy

from ..core.belnap import AtomState, Belnap

R0, R1, R2 = "R0", "R1", "R2"
TOOL_TIERS: dict[str, str] = {
    "pkg_query": R0,
    "file_read": R0,
    "config_get": R0,
    "service_status": R0,
    "cmdb_lookup": R0,
    "advisory_fetch": R0,
    "vex_lookup": R0,
    "run_scanner": R1,
    "request_approval": R1,
    "apply_patch": R2,
    "restart_service": R2,
    "disable_feature": R2,
}
DISRUPTIVE = tuple(t for t, tier in TOOL_TIERS.items() if tier == R2)
NON_DISRUPTIVE = tuple(t for t, tier in TOOL_TIERS.items() if tier != R2)

WORLD_GATE_ATOMS = ("present", "in_affected_range", "vuln_config_enabled")
CHANGE_GATE_ATOMS = ("change_approved", "rollback_available", "in_maintenance_window")
GATES: dict[str, tuple[str, ...]] = {
    "apply_patch": ("present", "in_affected_range", "change_approved", "rollback_available"),
    "disable_feature": ("present", "vuln_config_enabled", "change_approved"),
    "restart_service": ("change_approved", "in_maintenance_window"),
}
GATE_CONTEXT_ATOMS = tuple(sorted({a for atoms in GATES.values() for a in atoms}))


@dataclass(frozen=True)
class PolicyConfig:
    name: str  # P0 | P1 | P2 | P3
    k_world: int = 1
    k_change: int = 1
    evidence_gated: bool = True
    argument_gated: bool = True

    def k(self, atom: str) -> int:
        return self.k_world if atom in WORLD_GATE_ATOMS else self.k_change


POLICIES: dict[str, PolicyConfig] = {
    "P0": PolicyConfig("P0", evidence_gated=False, argument_gated=False),
    "P1": PolicyConfig("P1", evidence_gated=False, argument_gated=True),
    "P2": PolicyConfig("P2", k_world=1, k_change=1),
    "P3": PolicyConfig("P3", k_world=2, k_change=1),
    "P3k3": PolicyConfig("P3k3", k_world=3, k_change=1),  # (k, m) grid only
}


def render_cedar(cfg: PolicyConfig) -> str:
    if not cfg.argument_gated and not cfg.evidence_gated:
        return "// P0: no gating\npermit(principal, action, resource);\n"
    actions = ", ".join(f'Action::"{a}"' for a in NON_DISRUPTIVE)
    lines = [f"// {cfg.name}: generated by deepcti.policy.pdp.render_cedar"]
    lines.append(f"permit(principal, action in [{actions}], resource) when {{ context.args_ok }};")
    for action, atoms in GATES.items():
        conds = ["context.args_ok"]
        if cfg.evidence_gated:
            conds.append("context.args_in_scope")
            for atom in atoms:
                conds.append(f'context.atoms.{atom}.val == "T"')
                conds.append(f"context.atoms.{atom}.kpos >= {cfg.k(atom)}")
        body = " && ".join(conds)
        lines.append(f'permit(principal, action == Action::"{action}", resource) when {{ {body} }};')
    return "\n".join(lines) + "\n"


def write_policy_files(directory: str | Path) -> dict[str, Path]:
    out = {}
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    for name, cfg in POLICIES.items():
        path = directory / f"{name}.cedar"
        path.write_text(render_cedar(cfg), encoding="utf-8")
        out[name] = path
    return out


# ----------------------------------------------------------------------------- linter
def _leaves_of_conjunction(node: dict) -> list[dict] | None:
    """Return the leaves of a pure && tree, or None if any other boolean connective appears."""
    if "&&" in node:
        left = _leaves_of_conjunction(node["&&"]["left"])
        right = _leaves_of_conjunction(node["&&"]["right"])
        return None if left is None or right is None else left + right
    if any(op in node for op in ("||", "!", "if-then-else")):
        return None
    return [node]


def _attr_path(node: dict) -> list[str]:
    path = []
    while "." in node:
        path.append(node["."]["attr"])
        node = node["."]["left"]
    if node.get("Var") != "context":
        return []
    return list(reversed(path))


def _threshold_facts(leaves: list[dict]) -> tuple[set[str], dict[str, int]]:
    val_true: set[str] = set()
    kpos: dict[str, int] = {}
    for leaf in leaves:
        if "==" in leaf:
            path, value = _attr_path(leaf["=="]["left"]), leaf["=="]["right"].get("Value")
            if len(path) == 3 and path[0] == "atoms" and path[2] == "val" and value == "T":
                val_true.add(path[1])
        if ">=" in leaf:
            path, value = _attr_path(leaf[">="]["left"]), leaf[">="]["right"].get("Value")
            if len(path) == 3 and path[0] == "atoms" and path[2] == "kpos" and isinstance(value, int):
                kpos[path[1]] = max(kpos.get(path[1], 0), value)
    return val_true, kpos


def lint_policy(text: str, k_required: Mapping[str, int]) -> list[str]:
    """Check the T4 positive-threshold fragment for every permit reachable by a disruptive action."""
    errors = []
    ast = json.loads(cedarpy.policies_to_json_str(text))
    for pid, pol in ast.get("staticPolicies", {}).items():
        if pol["effect"] != "permit":
            continue
        scope = pol["action"]
        if scope["op"] == "All":
            reachable = set(DISRUPTIVE)
        elif scope["op"] == "==":
            reachable = {scope["entity"]["id"]} & set(DISRUPTIVE)
        else:
            reachable = {e["id"] for e in scope.get("entities", [])} & set(DISRUPTIVE)
        if not reachable:
            continue
        whens = [c["body"] for c in pol.get("conditions", []) if c["kind"] == "when"]
        leaves: list[dict] = []
        for body in whens:
            got = _leaves_of_conjunction(body)
            if got is None:
                errors.append(f"{pid}: disruptive permit uses a non-conjunctive condition")
                got = []
            leaves += got
        val_true, kpos = _threshold_facts(leaves)
        for action in sorted(reachable):
            for atom in GATES[action]:
                need = k_required.get(atom, 1)
                if atom not in val_true:
                    errors.append(f"{pid}/{action}: missing val(T) condition on {atom}")
                if kpos.get(atom, 0) < need:
                    errors.append(f"{pid}/{action}: kpos({atom}) threshold {kpos.get(atom, 0)} < {need}")
    return errors


# ----------------------------------------------------------------------------- evaluation
@dataclass
class AuthzDecision:
    allowed: bool
    tool: str
    tier: str
    policy: str
    reason: str
    context: dict = field(default_factory=dict)


def build_context(
    state: Mapping[str, AtomState], *, args_ok: bool, args_in_scope: bool
) -> dict:
    atoms = {}
    for atom in GATE_CONTEXT_ATOMS:
        item = state.get(atom)
        atoms[atom] = {
            "val": item.val.value if item else Belnap.N.value,
            "kpos": item.kappa_pos if item else 0,
            "kneg": item.kappa_neg if item else 0,
        }
    return {"args_ok": bool(args_ok), "args_in_scope": bool(args_in_scope), "atoms": atoms}


def reference_allowed(cfg: PolicyConfig, tool: str, context: dict) -> bool:
    if not cfg.argument_gated and not cfg.evidence_gated:
        return True
    if not context["args_ok"]:
        return False
    if tool not in GATES:
        return True
    if not cfg.evidence_gated:
        return True
    if not context["args_in_scope"]:
        return False
    for atom in GATES[tool]:
        item = context["atoms"][atom]
        if item["val"] != "T" or item["kpos"] < cfg.k(atom):
            return False
    return True


class PolicyDecisionPoint:
    """Complete mediation (A3): every tool call of every system goes through ``authorize``."""

    def __init__(self, cfg: PolicyConfig | str):
        self.cfg = POLICIES[cfg] if isinstance(cfg, str) else cfg
        self.text = render_cedar(self.cfg)
        self.log: list[AuthzDecision] = []

    def authorize(
        self, tool: str, state: Mapping[str, AtomState], *, args_ok: bool, args_in_scope: bool
    ) -> AuthzDecision:
        tier = TOOL_TIERS.get(tool, "unknown")
        context = build_context(state, args_ok=args_ok, args_in_scope=args_in_scope)
        if tier == "unknown":
            decision = AuthzDecision(False, tool, tier, self.cfg.name, "unknown tool", context)
            self.log.append(decision)
            return decision
        request = {
            "principal": 'Agent::"deepcti"',
            "action": f'Action::"{tool}"',
            "resource": 'Host::"target"',
            "context": context,
        }
        result = cedarpy.is_authorized(request, self.text, [])
        allowed = bool(result.allowed)
        ref = reference_allowed(self.cfg, tool, context)
        if allowed != ref:  # never silently trust either implementation
            raise RuntimeError(f"Cedar/reference disagreement for {tool}: cedar={allowed} ref={ref}")
        reason = "permit" if allowed else "deny"
        decision = AuthzDecision(allowed, tool, tier, self.cfg.name, reason, context)
        self.log.append(decision)
        return decision
