"""Dev validation of S3I (Inspect AI react) against S3 (home-made ReAct) on the same D1 dev cases.

    python -m deepcti.inspect_harness.validate_dev run    --models qwen3_14b mistral_small_24b
    python -m deepcti.inspect_harness.validate_dev report --models qwen3_14b mistral_small_24b

Case selection: 20 cases drawn (seed 0) from the 30 dev cases of runs/dev/E2_panel (where S3 already ran for every
panel model), so a fresh S3 rerun can also be compared with the frozen v2 S3 records (rerun-noise reference).
Both arms (tracker / withheld). S3 is rerun fresh with eval.runner.run_jobs; S3I with run_jobs_s3i.
"""

from __future__ import annotations

import argparse
import json
import random
from collections import Counter
from pathlib import Path
from statistics import mean

from ..eval import data
from ..eval.metrics import episode_metrics
from ..eval.runner import Job, Spec, run_jobs
from .s3i import LOG_ROOT, run_jobs_s3i

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "runs" / "dev" / "S3I_validation"
PANEL = ROOT / "runs" / "dev" / "E2_panel"
REPORT = ROOT / "results" / "v3" / "s3i_dev_validation.md"
ARMS = ("tracker", "withheld")
EXPERIMENT = "S3I_dev"


def read(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(x) for x in path.read_text(encoding="utf-8").splitlines() if x.strip()]


def select_cases(models: list[str], n: int = 20, seed: int = 0) -> list[dict]:
    common = None
    for m in models:
        ids = {r["case_id"] for r in read(PANEL / f"{m}.jsonl") if r["system"] == "S3"}
        common = ids if common is None else common & ids
    by_id = {c["case_id"]: c for c in data.load_cases("dev")}
    pool = sorted(i for i in (common or set()) if i in by_id)
    chosen = sorted(random.Random(seed).sample(pool, min(n, len(pool))))
    return [by_id[i] for i in chosen]


def jobs_for(system: str, model: str, cases: list[dict]) -> list[Job]:
    return [Job(Spec(EXPERIMENT, c["case_id"], system, model, arm, policy="P1"), c) for c in cases for arm in ARMS]


def cmd_run(models: list[str], concurrency: int) -> None:
    cases = select_cases(models)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "cases.json").write_text(json.dumps([c["case_id"] for c in cases], indent=1), encoding="utf-8")
    for m in models:
        s3 = run_jobs(jobs_for("S3", m, cases), OUT / f"{m}.S3.jsonl", model_name=m, concurrency=concurrency)
        print("S3", m, s3, flush=True)
        s3i = run_jobs_s3i(jobs_for("S3I", m, cases), OUT / f"{m}.S3I.jsonl", model_name=m,
                           concurrency=concurrency, log_dir=LOG_ROOT / "s3i" / EXPERIMENT / m)
        print("S3I", m, s3i, flush=True)


def _latest(records: list[dict]) -> dict[tuple, dict]:
    out = {}
    for r in records:
        if r.get("error") is None:
            out[(r["case_id"], r["arm"])] = r
    return out


def _summ(recs: list[dict], labels: dict) -> dict:
    ms = [episode_metrics(r, labels) for r in recs]
    n = len(ms)
    return {
        "n": n,
        "acc": mean(m["correct"] for m in ms) if n else float("nan"),
        "loss": mean(m["loss"] for m in ms) if n else float("nan"),
        "invalid": sum(m["invalid"] for m in ms),
        "dangerous": sum(m["dangerous"] for m in ms),
        "unauth": sum(m["unauthorized_exec"] for m in ms),
        "cost": mean(r["cost"] for r in recs) if n else float("nan"),
        "calls": mean(r["n_calls"] for r in recs) if n else float("nan"),
        "forced": sum(bool((r.get("extra") or {}).get("forced_submit")) or
                      any(isinstance(t, dict) and "forced_submit" in t for t in r.get("trace", [])) for r in recs),
        "tokens": mean(r["usage"]["prompt_tokens"] + r["usage"]["completion_tokens"] for r in recs) if n else 0,
    }


def cmd_report(models: list[str]) -> None:
    labels = data.load_labels("dev")
    case_ids = json.loads((OUT / "cases.json").read_text(encoding="utf-8"))
    gold = Counter(labels[c]["label"]["status"] for c in case_ids)
    lines = [
        "# S3I (Inspect AI `react()`) vs S3 (home-made ReAct): D1 dev validation",
        "",
        "Generated by `python -m deepcti.inspect_harness.validate_dev report`. Dev split only; labels from "
        "`deepcti.eval.data.load_labels('dev')`, metrics from `deepcti.eval.metrics.episode_metrics` (miss cost 10).",
        "",
        f"* Cases: {len(case_ids)} D1 dev cases drawn (seed 0) from the 30 dev cases of `runs/dev/E2_panel`; "
        f"gold status mix {dict(gold)}; both arms (tracker, withheld) -> {2 * len(case_ids)} episodes per "
        "system x model.",
        "* S3 = fresh rerun of the v2 ReAct loop with the current code (`eval.runner.run_jobs`); "
        "S3-v2 = the frozen v2 dev records in `runs/dev/E2_panel` (same cases), shown as a rerun-noise reference.",
        "* S3I = `src/deepcti/inspect_harness/s3i.py` (Inspect AI 0.3.276 `inspect_ai.agent.react`), same tools via "
        "`Mediator.execute`, same system prompt / task message / budget (60) / submit schema / policy (P1), "
        "temperature 0. Inspect logs: `logs/inspect/s3i/S3I_dev/<model>/*.eval`.",
        "* Records: `runs/dev/S3I_validation/<model>.{S3,S3I}.jsonl` (runner JSONL schema).",
        "* Held equal: tool names/descriptions/JSON schemas (Inspect additionally requires a per-parameter "
        "description; the parameter's own name is used), complete mediation through the PDP, call-id-prefixed outputs "
        "truncated at 3000 chars, budget 60 with S3's 'budget exhausted' text, <= 20 model turns, <= 2 nudges, one "
        "forced `submit_decision`, vLLM endpoint / extra_body / max_tokens 1024. Harness-native (kept): Inspect's "
        "continue prompt, Inspect's tool-argument schema validation, Inspect's API retry policy.",
        "* How to read the agreement table: temperature-0 decoding on a batched vLLM server is not bitwise "
        "deterministic, so `S3 vs S3-v2` (same loop, rerun) is the noise floor against which `S3I vs S3` "
        "(different harness) should be judged.",
        "",
    ]
    for m in models:
        s3 = _latest(read(OUT / f"{m}.S3.jsonl"))
        s3i = _latest(read(OUT / f"{m}.S3I.jsonl"))
        old: dict = {}
        for r in read(PANEL / f"{m}.jsonl"):
            if r["system"] == "S3" and r.get("error") is None and r["case_id"] in case_ids:
                old[(r["case_id"], r["arm"])] = r
        lines += [f"## {m}", "",
                  "| arm | system | n | accuracy | mean loss | invalid | dangerous | unauth. exec | mean cost | "
                  "mean calls | forced submit | mean tokens |",
                  "|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for arm in (*ARMS, "both"):
            for name, recs in (("S3", s3), ("S3I", s3i), ("S3-v2", old)):
                sel = [r for (c, a), r in sorted(recs.items()) if arm == "both" or a == arm]
                s = _summ(sel, labels)
                lines.append(f"| {arm} | {name} | {s['n']} | {s['acc']:.3f} | {s['loss']:.3f} | {s['invalid']} | "
                             f"{s['dangerous']} | {s['unauth']} | {s['cost']:.1f} | {s['calls']:.1f} | "
                             f"{s['forced']} | {s['tokens']:.0f} |")
        lines += ["", "Agreement on the emitted status (invalid outputs counted as their own category):", ""]
        lines += ["| pair | arm | n paired | status agreement | both correct | only first correct | "
                  "only second correct | both wrong | mean loss diff (first - second) |", "|---|---|---|---|---|---|---|---|---|"]
        for (n1, a1), (n2, a2) in ((("S3I", s3i), ("S3", s3)), (("S3", s3), ("S3-v2", old)),
                                   (("S3I", s3i), ("S3-v2", old))):
            for arm in (*ARMS, "both"):
                keys = sorted(k for k in a1 if k in a2 and (arm == "both" or k[1] == arm))
                if not keys:
                    continue
                m1 = {k: episode_metrics(a1[k], labels) for k in keys}
                m2 = {k: episode_metrics(a2[k], labels) for k in keys}
                agree = sum((m1[k]["pred"] or "invalid") == (m2[k]["pred"] or "invalid") for k in keys)
                bc = sum(m1[k]["correct"] and m2[k]["correct"] for k in keys)
                o1 = sum(m1[k]["correct"] and not m2[k]["correct"] for k in keys)
                o2 = sum(m2[k]["correct"] and not m1[k]["correct"] for k in keys)
                bw = len(keys) - bc - o1 - o2
                dl = mean(m1[k]["loss"] - m2[k]["loss"] for k in keys)
                lines.append(f"| {n1} vs {n2} | {arm} | {len(keys)} | {agree}/{len(keys)} ({agree / len(keys):.0%}) | "
                             f"{bc} | {o1} | {o2} | {bw} | {dl:+.3f} |")
        diffs = []
        for k in sorted(set(s3) & set(s3i)):
            p1, p2 = episode_metrics(s3i[k], labels), episode_metrics(s3[k], labels)
            if (p1["pred"] or "invalid") != (p2["pred"] or "invalid"):
                diffs.append(f"| {k[0]} | {k[1]} | {p1['gold']} | {p2['pred'] or 'invalid'} | "
                             f"{p1['pred'] or 'invalid'} | {s3[k]['n_calls']} | {s3i[k]['n_calls']} |")
        if diffs:
            lines += ["", "Disagreements S3 vs S3I:", "", "| case | arm | gold | S3 | S3I | S3 calls | S3I calls |",
                      "|---|---|---|---|---|---|---|", *diffs]
        lines.append("")
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(REPORT)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["run", "report"])
    ap.add_argument("--models", nargs="+", default=["qwen3_14b", "mistral_small_24b"])
    ap.add_argument("--concurrency", type=int, default=16)
    a = ap.parse_args()
    if a.cmd == "run":
        cmd_run(a.models, a.concurrency)
    else:
        cmd_report(a.models)


if __name__ == "__main__":
    main()
