"""prereg-v2 analyses: X4 (DC v2.1 drift study, H7/H8) and the panel addendum summary.

  python scripts/paper/analyze_addendum.py --split test --allow-sealed
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts" / "paper"))

from analyze import cluster_bootstrap, cluster_signflip, holm, write  # noqa: E402
from summarize import load_runs, summary  # noqa: E402

from deepcti.eval import data  # noqa: E402


def x4(split: str, allow: bool, md: list[str]) -> dict:
    df = load_runs(split, "X4", allow)
    if df.empty:
        return {}
    eps = {e["episode_id"]: e for e in data.read_jsonl(ROOT / "data" / "d2" / f"{split}.jsonl")}
    cve_of = {c["case_id"]: c["cve"] for c in data.load_cases(split)}
    df["kind"] = df["drift"].map(lambda d: eps.get(d, {}).get("kind"))
    ok = df[~df["error"]]
    tab = ok.groupby(["kind", "system"]).agg(n=("loss", "size"), acc=("correct", "mean"), loss=("loss", "mean"),
                                             DER=("dangerous", "mean"), cost=("cost", "mean")).round(3)
    write(tab, "x4_by_kind", split)
    md += ["## X4 — DC v2.1 drift study (D2 test; spec v3)", "", tab.to_markdown(), ""]
    tests = {}
    piv = ok[ok["system"].isin(["DC", "DCv21"])].pivot_table(index=["drift", "model", "kind"], columns="system",
                                                              values="loss").dropna().reset_index()
    piv["cve"] = piv["drift"].map(lambda e: cve_of.get(eps.get(e, {}).get("case_id"), e))
    piv["d"] = piv["DCv21"] - piv["DC"]
    unr = piv[piv["kind"] == "upgrade_no_restart"]
    if len(unr):
        lo, hi, _ = cluster_bootstrap(unr, lambda s: s["d"].mean(), n=4000)
        tests["H7 DCv21−DC loss (upgrade_no_restart)"] = {"estimate": float(unr["d"].mean()), "ci95": [lo, hi],
                                                         "p": cluster_signflip(unr), "n": len(unr)}
    rest = piv[piv["kind"] != "upgrade_no_restart"]
    if len(rest):
        _, _, arr = cluster_bootstrap(rest, lambda s: s["d"].mean(), n=4000)
        ub = float(np.percentile(arr, 95))
        tests["H8 DCv21−DC loss (other kinds), one-sided 95% UB < 0.05"] = {
            "estimate": float(rest["d"].mean()), "upper95": ub, "non_inferior": bool(ub < 0.05),
            "p": float(np.mean(arr >= 0.05)), "n": len(rest)}
    if tests:
        adj = holm({k: v["p"] for k, v in tests.items()})
        rows = [{"test": k, **v, "p_holm": adj[k]} for k, v in tests.items()]
        t = pd.DataFrame(rows)
        write(t, "x4_hypotheses", split)
        md += ["Pre-registered H7/H8 (Holm over the two; H8 p = bootstrap share of draws ≥ margin):", "",
               t.round(4).to_markdown(index=False), ""]
    return tests


def panel(split: str, allow: bool, md: list[str]) -> None:
    for exp in ("E2", "E4", "E9"):
        df = load_runs(split, exp, allow)
        if df.empty:
            continue
        tab = summary(df, ["arm", "system", "model"] if exp == "E2" else ["system", "model"])
        write(tab, f"panel_{exp.lower()}", split)
        md += [f"## Panel ({exp}, all models incl. addendum)", "",
               tab[["n", "acc", "loss", "DER", "invalid"]].to_markdown(), ""]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", required=True)
    ap.add_argument("--allow-sealed", action="store_true")
    args = ap.parse_args()
    md = ["# prereg-v2 analyses (generated by scripts/paper/analyze_addendum.py)", ""]
    x4(args.split, args.allow_sealed, md)
    panel(args.split, args.allow_sealed, md)
    out = ROOT / "results" / "v3" / args.split / "ADDENDUM.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(md), encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
